### ISSUE TITLE
Add third batch of icons

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10231]
See this comment https://github.com/mozilla-mobile/fenix/issues/18132#issuecomment-833184740

- [x] help
- [x] folder
- [x] folder add/new
- [x] share (the Android symbol is three circles connected with lines)
- [x] collection
- [x] add to home screen
- [x] password (eye)
- [x] password hide (eye with cross)
- [x] checkmark
- [x] website placeholder (this is not just used for generic website, but also for Settings menu items like “Exceptions”
- [ ] edit
- [x] sync (it’s already using the right icon, just needs to point the other way – counterclockwise – and the icon has been updated to reflect that)

### Permissions

- [x] location
- [x] location blocked
- [x] camera
- [x] camera blocked
- [x] microphone
- [x] microphone blocked
- [x] notifications
- [x] notifications blocked
- [x] storage
- [x] storage blocked
- [x] autoplay media
- [x] autoplay media blocked

Make sure that DRM-controlled content is using the new `link` icon – I think it already does?

### Tracking Protection

- [x] cryptominer
- [x] fingerprinter
- [x] social tracker
- [x] third party cookies

### New Tab Page

- [x] avatar signed out (on New Tab Page, see https://github.com/mozilla-mobile/fenix/issues/18132#issuecomment-832368781 above)
- [x] info (on New Tab Page, see https://github.com/mozilla-mobile/fenix/issues/18132#issuecomment-832368781 above. The other `info` icon e.g. in Add-ons Manager seems to be correct already)

#### Add-ons Manager

- [ ] rating (small - 16x16 – in Add-ons Manager)
- [ ] rating half (small - 16x16 – in Add-ons Manager)

**Comment by brampitoyo** [comment]
@Amejia481 Just a note before we get started: both the `share` and `edit` icons are currently being finalised. They’re due to be delivered soon. I’ll let you know as soon as they’re ready, so you can start adding them in :-)

**Comment by brampitoyo** [comment]
@Amejia481 Thanks for making these changes! Just a few issues remaining:

-----

- [ ] share

Sorry, this icon has just been redrawn and finalised today. [Figma](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=3221%3A37) (you’ll notice that it’s positioned to the side of all other icons).

-----

- [ ] password (eye)
- [ ] password hide (eye with cross)

These icons seem to not be coloured like all the other ones. They seem to have a little bit of transparency added. Was this intentional? If yes, then we’re all good to go. If no, then I think we should make the icon fill identical to all other icons.

-----

### Tracking Protection

It seems like I couldn’t find these icons where they would normally appear: Settings → ETP → Info. Do we not show icons there? Are there other places where these tracker type icons are shown?

-----

### Add-ons Manager

- [ ] rating (small - 16x16 – in Add-ons Manager) [Figma](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=3041%3A7)
- [ ] rating half (small - 16x16 – in Add-ons Manager) Figma: [light theme](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=3041%3A34), [dark theme](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=3041%3A71), [shape only](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=3229%3A0).

For the rating half icon, I provided separate assets for light and dark themes, as well as a shape-only asset that you can manually colourise. Let me know if this isn’t the correct way to implement it, and I’ll be happy to generate a version that works!

**Comment by brampitoyo** [comment]
I also found one icon from the previous batch that was not yet replaced: password (key symbol). Wonder whether I’ve forgotten to include it on the previous list? If so, then that’s my mistake – sorry about this!

The new password icon can be found in this [Figma](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=2326%3A48).

<img width="360" src="https://user-images.githubusercontent.com/51007/117918805-eae32b80-b33f-11eb-85bf-5a69beaf890e.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/117918872-0bab8100-b340-11eb-883d-4c2b83874ac6.png">

**Comment by Amejia481** [comment]
Thanks for the review, I performed the following updates:

*  Share.
* Website placeholder

Notes:
* The  password (eye) and password hide (eye with cross) icons, the previous versions already had the transparency on them, If you like I can remove them, I think the transparency was added before to match the Android equivalents.

* The tracking Protection icons were removed on following this request https://github.com/mozilla-mobile/fenix/issues/13812#issuecomment-692929699, not sure if I should I added then back?  I think we are not showing them in other screens.

**Comment by brampitoyo** [comment]
Thanks, @Amejia481!

- If password and password-hide has transparency to match Android System style, we shouldn’t change that. Let’s keep it intact.
- I missed the fact that the Tracking Protection tracker-type icons were removed late last year. It sounds like iOS is the platform that needs to catch up to Fenix. So, let’s not add the icon, and I will make sure that we are removing the icon on iOS. Thanks for posting the link to that issue!

**Comment by Amejia481** [comment]
I'm created a separated issue for updated the [rating icon ](https://github.com/mozilla-mobile/android-components/issues/10255) as It's taking too much time, it will be better to address it separately, and not block other icons on it.
