### ISSUE TITLE
Adding sync ping

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1036]
We may (needs discussion) want to add the sync ping to the telemetry library (to collect data about the performance of the new sync components).

Docs:
https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/sync-ping.html

Open questions:
* Do we need that for any of our apps? Do we want that in the reference browser?
* How soon will something like this be possible with the new telemetry SDK?
* How will the sync component(s) provide the data for those pings?

**Comment by grigoryk** [comment]
Since sync ping is largely how we monitor health of our sync implementations, at the very least we'd want this in any application that interacts with the sync1.5 ecosystem.

Fennec's sync ping implementation (the roll-up/upload/scheduling bits) are basically correct at this point. Taking a brief look at the telemetry code, it seems like at lot of it was borrowed from Fennec, so that's a good starting point.

In Fennec we had an annoying complicated way to get sync ping data out of sync code (due to build issues around background services), so that complexity will be done away with.

**Comment by grigoryk** [comment]
Ah, I think I missed the "new telemetry SDK" bit - is that going to be significantly different from what the current telemetry code is? @pocmo

**Comment by pocmo** [comment]
Yep, that is going to be a complete re-write. A major difference is that there won't be static ping types anymore. Instead there are high-level metric types that the app can collect, see draft:
https://docs.google.com/document/d/186GI_2ljdqWqWTBk5P3QjHD3BwpMyd8kRayRAuz1-dk

**Comment by pocmo** [comment]
The `service-telemetry` is deprecated.
