### ISSUE TITLE
Handle and log RemoteTabProviderException in RemoteTabsStorage

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#10382]
Filing this to discuss as part of investigation for https://github.com/mozilla/application-services/issues/4035.

`RemoteTabProviderException` thrown in `setLocalTabs` sometimes causes crashes, and sometimes gets caught and logged.

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11496531/ (Caught and logged)
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8825532/ (Recent crash spike)

What's causing this difference? Should we catch it and log with our crash reporter?

**Comment by jonalmeida** [comment]
The exception we see in Sentry leaves the Kotlin stacktrace [here](https://searchfox.org/mozilla-mobile/rev/093a6d8c1f0d3613224274432f02779429aef2a6/application-services/components/tabs/android/src/main/java/mozilla/appservices/remotetabs/rust/RustError.kt#44).

Reading into the [PoisionError](https://doc.rust-lang.org/std/sync/struct.PoisonError.html) docs, that looks beyond our Fenix/AC control when it affects the internals of the rust SyncManager.

My understanding of why this has shown up at least twice in the past with `RemoteTabsProvider.setLocalTabs` in the stack, is probably because we are [the first feature](https://github.com/mozilla-mobile/fenix/blob/e69bf4e26a3df54a545a59b69852c51571e65520/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt#L187) that is registered on the account manager which has an effect on the internal SyncManager. So with the current handling technique, the first consumer will get receive the native trace as part of their own `intoException`.

**Comment by csadilek** [comment]
So the difference here is due to `androidx.work.CoroutineWorker` wrapping `doWork` in a catch-all. So, all exceptions are being handled if `RemoteTabsStorage` is being called from our `WorkManager` task.

However, when calling `RemoteTabsStorage` directly e.g. via `SyncedTabsFeature` we don't have a catch-all and are crashing..

**Comment by jonalmeida** [comment]
Let's do this before https://github.com/mozilla-mobile/android-components/pull/10475/ lands.
