### ISSUE TITLE
Conflicts in errorpages strings with Focus and friends

### ISSUE THREAD

**Issue by Pike** [mozilla-mobile/android-components#1056]
In the error pages strings, `error_generic_message` and `error_generic_title` differ from what they are in Focus and Firefox for TV.

This is bad for cross-channel/product.

@pocmo, do you have a suggestion on how to reconcile this? 

CC @delphine.

**Comment by jonalmeida** [comment]
@Pike thanks for filing the issue! This was meant to be a follow up issue from the main feature implementation where we prefix our string resources with `mozac_` to avoid collisions.

**Comment by pocmo** [comment]
Yeah, there are two things:

* Eventually we would like to translate those strings here and then there will be no need to have them in the apps anymore because the `errorpages` component would come with strings. For that we would like to prefix the strings to avoid collisions as @jonalmeida said.

* In the meantime: I wonder why there's the need for having a different string in the components right now. Let's just use what Focus/Fire-TV uses and then file a separate issue to update it once we actually have an L10N setup and a new string name.
