### ISSUE TITLE
BrowserGestureDetector: Reflective access to mSpanSlop will throw an exception when targeting API 30

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10638]
Thew new lint is complaining:

> android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt:64: Error: Reflective access to mSpanSlop will throw an exception when targeting API 30 and above [SoonBlockedPrivateApi]
                javaClass.getDeclaredField("mSpanSlop"),

**Comment by pocmo** [comment]
This will be a problem.

CC @Mugurell 

For now I'll suppress (`compose`) branch. But I guess we will have to address this somehow.

**Comment by Mugurell** [comment]
We use that to favor a bit more identifying touches as zoom motions.
Those properties control the distance we wait for before trying to identify between zooming and panning gestures.
Even with this right now we can see the toolbar moving just a little when actually doing a zooming gesture (a few pixels means panning, after more we can detect the zoom gesture).
Without halving these values but with otherwise the same code the toolbar will move just a little bit more and the effect would be more easy to spot.

To get past this issue if also moving to Compose with clean slates maybe we could use some state from GeckoView about scroll and overscroll distance.
