### ISSUE TITLE
Enhance RequestInterceptor to load alternative URL

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#1106]
We already support providing an `InterceptionResponse` to load custom data instead of loading the requested URL. This enhancement would allow returning an alternative URL to be loaded. This is really useful when integrating FxA in the reference browser where we want to show a custom success page after successfully intercepting the OAuth redirect URL. I can do that with a content redirect as a workaround, but using Gecko that will briefly display the data URL in the toolbar.

**Comment by jonalmeida** [comment]
Our `ErrorResponse` already does something like this (optional url), so it should be similar where we just do the same with `InterceptionResponse`

```kotlin
/**
 * An alternative response for an intercepted request.
 */
data class InterceptionResponse(
    val data: String,
    val mimeType: String = "text/html",
    val encoding: String = "UTF-8"
)

/**
 * An alternative response for an error request.
 */
data class ErrorResponse(
    val data: String,
    val url: String? = null,
    val mimeType: String = "text/html",
    val encoding: String = "UTF-8"
)
```

So in the `GeckoEngineSession#onLoadRequest` for Gecko, you check if the url is not-null and call `loadUrl` otherwise do what it currently does.

For WebView, we do this in `SystemEngineView#shouldInterceptRequest`.

I'm adding this issue for Hacktoberfest in case someone is looking for small but interesting issue to fix in case we take time to get this done.
