### ISSUE TITLE
Submit GeckoView crashes with EXTRA_CRASH_BACKGROUND == true automatically

### ISSUE THREAD

**Issue by jamienicol** [mozilla-mobile/android-components#11358]
In https://phabricator.services.mozilla.com/D132809 an extra field `EXTRA_CRASH_BACKGROUND` will be added to GeckoView crash intents, specifying that the crash occurred in a background process causing minimal if any disruption to the user. For example the GPU process (which is currently being implemented). The intention is that we can choose to submit these reports automatically rather than displaying the crash reporter UI to the user.

cc @csadilek

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18809)

**Comment by jamienicol** [comment]
bz-1743454 has now landed in mozilla-central. We made a slight change to the API I wrote in the first comment. Instead of adding a new boolean `EXTRA_CRASH_BACKGROUND` field alongside `EXTRA_CRASH_FATAL`, we have deprecated `EXTRA_CRASH_FATAL` and added a new `EXTRA_CRASH_PROCESS_TYPE`.

This is a String, whose value will be equal to one of the constants:
* `CRASHED_PROCESS_TYPE_MAIN` - corresponds to the old `fatal == true`
* `CRASHED_PROCESS_TYPE_FOREGROUND_CHILD - content process crash, corresponds to the old `fatal == false`
* `CRASHED_PROCESS_TYPE_BACKGROUND_CHILD - this is the new type used by GPU process crashes which we want to automatically submit.

**Comment by agi** [comment]
Discussed this with @csadilek . Right now, content crashes display a tab blocking UI that lets the user submit a crash report and restore the tab. This UI works well for content crashes as it doesn't stop the user from switching tab and tell them which tab(s) is responsible for the crash.

<img src="https://user-images.githubusercontent.com/69051186/158257514-09b16a8e-e47d-4a5d-924c-3478beaa575d.jpg" width=300 />

For GPU process crashes, however, we don't have a tab to point to and we don't really _need_ to block the user from interacting with the page, so I think what we should do is intercept the intent for `BACKGROUND_CHILD` crashes (which are basically GPU crashes right now) and show a notification, otherwise letting users interact with the browser as normal. The notification would have a button on it that lets the user submit the crash report if they so desire.

The notification might say something like "Sorry. A problem occurred in Firefox <Report>". Here's a screenshot for the main process crash, we would probably want to do something very similar.

<img src="https://user-images.githubusercontent.com/69051186/158257527-01f3ff06-6ccf-4367-8ea1-373fcc307dc0.jpg" width=300 />

Would that work for you @jamienicol @Mugurell ?

**Comment by jamienicol** [comment]
Yep, that sounds really good to me!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792899

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
