### ISSUE TITLE
Generate javadoc

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#120]
* .. and host it somewhere
* .. and upload javadoc artifact to jcenter? Is this something the IDE needs to provide documentation?

**Comment by csadilek** [comment]
We don't need it for the IDE, because we publish sources and the IDEs will automatically download the sources JAR. So, JavaDoc will always be there for our users. Yay open source!

But, we should still generate javadoc. Easiest solution is to generate them into the /doc folder on master and enable GitHub pages for our repository.
