### ISSUE TITLE
Allow for notifying consumers on unsuccessful Save to PDF requests

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#12642]
In at least two cases in in the `GeckEngine.requestPdfToDownload`, we can unsuccessfully return a PDF. Our current error handling in https://github.com/mozilla-mobile/android-components/pull/12277 is to silently fail, but this might not be helpful to users if they are expecting to see a PDF.

We should come up with a solution, possibly similar to the Download State one, for handling the error cases so that we can notify consumers.

cc: @Amejia481 , @ohall-m

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21285)

**Comment by ohall-m** [comment]
Adding more info from the GV change in [bug 1784554 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1784554) - the new GV change will now return the input stream as early as possible. Because of this, if a failure occurs late, the `InputStream` will [now send an IO error](https://searchfox.org/mozilla-central/rev/ffa4d00965c5281def6d3ddcbcdf6259d38c9b9a/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoInputStream.java#129,161,166-167). Before, the `GeckoResult` that held the input stream would be the exception. The `GeckoResult` can still have an exception too with this change, if the failure happens early enough.

I checked that this new IO exception is covered on some level before landing in GV, I believe [here](https://github.com/mozilla-mobile/android-components/blob/c7eefe7d6c8913198b9656f304b2f91deb213519/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L775). Not sure how this failure looks on the UI side. 

Error States:
* `GeckoResult` [Exceptions](https://searchfox.org/mozilla-central/rev/ffa4d00965c5281def6d3ddcbcdf6259d38c9b9a/widget/android/nsWindow.cpp#1779,1789,1803) - _permalinked before landing 1784554, but these exceptions stay the same_
* `InputStream` `IO` [Exception](https://searchfox.org/mozilla-central/rev/ffa4d00965c5281def6d3ddcbcdf6259d38c9b9a/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoInputStream.java#129,161,166-167)

**Comment by jonalmeida** [comment]
> * `GeckoResult` [Exceptions](https://searchfox.org/mozilla-central/rev/ffa4d00965c5281def6d3ddcbcdf6259d38c9b9a/widget/android/nsWindow.cpp#1779,1789,1803) - _permalinked before landing 1784554, but these exceptions stay the same_
> 
> * `InputStream` `IO` [Exception](https://searchfox.org/mozilla-central/rev/ffa4d00965c5281def6d3ddcbcdf6259d38c9b9a/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoInputStream.java#129,161,166-167)

@ohall-m doesn't this mean that `GeckoSession.saveAsPdf()` can now throw exceptions outside of the `GeckoResult` return value? If so, we should annotate the Java API so mention that it now throws an exception. IIRC, that will help consumers catch that this needs to be handled with build warnings.

**Comment by ohall-m** [comment]
Good point! `GeckoInputStream` inherits from `InputStream` and  uses the `throws` keyword to mark the exception, so the compiler will require handling the `IOException`. The `IOException` can only happen when reading/writing. Did a quick check to make sure. I don't know if there is a way right now to directly annotate the wrapped `InputStream`'s exception in the API too, since it isn't the return value.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796482

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
