### ISSUE TITLE
Session.canGoForward is not updated until page has nearly finished loading

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/android-components#1311]
After calling `SessionUseCases#goBack`, `Session.Observer#onNavigationStateChanged` is not called until the previous page has almost finished loading.  As a user, I would expect this change to be immediate (we already have the forward stack available, we should be able to cancel loading and go forward at any time).

In Firefox for Fire TV this results in a very sluggish change to our foward button (see the gif below)

![image](https://user-images.githubusercontent.com/13170306/48234973-b65a1780-e370-11e8-9e63-15293e2c7844.png)

**Comment by pocmo** [comment]
WebView: I was expecting us to maybe call `onNavigationStateChange` from `onPageFinished` and that's why it's late. However the only place we seem to call it in `browser-engine-system` seems to be from `onReceivedTitle()`. That's a bit odd. I wonder if we can/should (additional to the fix mentioned above) call it from `onPageStarted` and `onPageFinished`. The `Session` will take care of not notifying app/UI if the state hasn't actually changed so there shouldn't be any issue with doing it more often in `browser-engine-system`.

**Comment by jonalmeida** [comment]
@pocmo we moved it out from `onPageStarted` because that would only notify observers when the full page was loaded. This was an issue for FireTV on slow/large sites where the page takes time and the navigation buttons weren't available until then. See https://github.com/mozilla-mobile/android-components/pull/746

If we're fine with the solution there, maybe we need to notify observers if they can go back in the `onPageStarted`. Otherwise, we should figure out a different way to notify them sooner.

**Comment by pocmo** [comment]
> We could try to move it to onPageStarted, but iirc that was too early to make the call.

Why is it too early if the navigation stack has actually changed?

**Comment by jonalmeida** [comment]
It was silly of me to not document why `onPageStarted` wasn't viable when I first did my research:

The reason being is that `canGoForward`/`canGoBack` can be wrong sometimes depending on the page load. So notifying observers in `onReceivedTitle` was a good enough time when the page had begun loading and we knew for sure the results would come back correctly. It was also a callback that was fired only once instead of polluting the observers with constant notifications if we did `onProgressChanged`, for example.

If you moved the callback to `onPageStarted`, toggling back and forward before a page finished loading shows that you can continue going back/forward even though there are no back/forward results.

In my tests so far, a healthy in-between solution might be to fire the callback in `onPageStarted` AND `onReceivedTitle`. It seems responsive and accurate.
