### ISSUE TITLE
Update to Gradle 5.2.1

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1499]
This will likely require a new Android plugin first. But filing this already.

https://docs.gradle.org/5.0/release-notes.html

**Comment by pocmo** [comment]
Did a quick test. The `assemble` and `test` tasks pass with Gradle 5.0.

**Comment by pocmo** [comment]
With 5.1 we may be running into this:
https://sea-region.github.com/dcendents/android-maven-gradle-plugin/issues/80

**Comment by mcomella** [comment]
> This will likely require a new Android plugin first. But filing this already.

fwiw, the Android plugin specifies a required minimum version but not a maximum version so in theory, you shouldn't need to upgrade the android gradle plugin to update gradle (though since gradle 5.0 has breaking changes, maybe for this upgrade that is not the case). In fact, there are some benefits to being on the newest version (faster compiles, bug fixes, etc. – I wonder if the gradle parallel bug is fixed in the latest versions?).

fwiw, Gradle v5.2.1 is out now – since so many versions have passed from v5.0, things might be more stable now. We're running v5.2 on Echo Show.

**Comment by pocmo** [comment]
Okay, I rewrote the way we create the maven artifacts and replaced some removed API usage with new code. The last thing I'm aware of is fixing our dokka configuration wish fails.
