### ISSUE TITLE
Toolbar: add a simple implementation that manages nested scrolling, progress bar

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#198]
My needs:
- Implement a specific toolbar layout (that doesn't match Android components, e.g. menu button needs to be removed)
- Toolbar scrolls off screen when the WebView is scrolled down and comes back on scroll up
- A progress bar

I feel these are needs other projects may see but the toolbar in Android components, afaict, is too inflexible to allow this. **It would be great if there was a simple component that managed nested scrolling and provided a progress bar but allowed me to provide a custom layout.** Perhaps this component can be composed of other existing components (menu button, url bar, https status, etc.) rather then being hard-coded to support these features (as it is now)?

**Comment by pocmo** [comment]
> but the toolbar in Android components, afaict, is too inflexible to allow this.

The toolbar is only a couple of days old and not even close to a shape we want it to be in.... you are asking for too much too early here. :)

> Perhaps this component can be composed of other existing components (menu button, url bar, https status, etc.) rather then being hard-coded to support these features (as it is now)?

That's how we are building the current toolbar (As said it's still early) and things like the menu are already optional and composed from other components. :) Other high-level components only depend on the interface in 'concept-toolbar' so that consumers could build their own implementation using only some of the components if it diverges too much from the default toolbar implementation provided.

**Comment by pocmo** [comment]
I've filed multiple issues that are related to this one:

* #201 - Toolbar: Support nested scrolling / toolbar fading away
* #202 - Toolbar: Allow different "display" layouts.
