### ISSUE TITLE
Instantiate Session without an initial url

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/android-components#1993]
On Firefox TV, we want to pre-load the WebView for performance, but we don't have a url. Currently, we're using "firefox:home" but it makes our history management difficult, so we'd like to be able to get a Session (and instantiate a webview) without an initial url.

https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/MainActivity.kt#L108

**Comment by pocmo** [comment]
> we want to pre-load the WebView for performance

Just curious: What kind of performance gain are you seeing from creating an empty WebView early?

**Comment by liuche** [comment]
@Baron-Severin has mentioned that it seems to take ~1s to create the webview (especially on the slower Amazon devices), but we could do some perf measurements if that's something specific you'd like to have!

**Comment by pocmo** [comment]
It's a larger change for us, so I'm trying to understand the trade-offs.

We have been in a similar situation at some point too. I think in some places we have been using `about:blank` sessions. But that obviously doesn't help you (although I wonder what `Session("")` would result in.

Overall I think it makes perfectly sense to want to start with an "empty session". It will have a ripple effect through AC and our apps though; since no one is expecting a `null` URL right now (yay Kotlin!). :)
