### ISSUE TITLE
Add capability for adding/overriding params in Browser-Search component

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/android-components#2075]
Talked to @csadilek about this, and we'd like to be able to override or add custom params to the Browser Search component.

Specifically, we'd like to have more control over the search url, such as the ability to override specific params (or include our own custom params) when using the search component. Currently it looks like the params are defined in [xml files](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/assets/searchplugins/amazon-au.xml#L9) so if we could hook into there by a) providing our own xml to override/use, b) override specific params, c) add params during the [param parsing](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngine.kt#L57), or also open other options.

**Comment by pocmo** [comment]
> f we could hook into there by a) providing our own xml to override/use, b) override specific params, c) add params during the [param parsing](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngine.kt#L57), or also open other options.

* Option (a) is already possible:
  *  You can pass a list of `SearchEngineProvider` to `SearchEngineManager`. By default the list only contains `AssetsSearchEngineProvider` which loads the default list of search engines from assets. You can implement a custom `SearchEngineProvider` and provide your own search engines.
  * `AssetsSearchEngineProvider` itself allows to specify filters (to remove search engines) and add additional identifiers (that will get loaded as XML from assets). For example Focus uses that to add "DuckDuckGo" for all locales and remove Bing as well as search engines the user has removed/hidden: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/Components.kt#L36-L37

* Option (B) and (C): Overriding or adding params is something we do not support yet. But we could add that. With all the different plugins that may end up being a complicated setup.

Overall it would be nice if we could come up with a solution that doesn't require too much customization. The big advantage of the `browser-search` component is that not every app needs to set this up manually. If apps start to ship their own search XML files then we end up with the same fork-copy mess again.

Also see #1719: Since desktop is moving away from OpenSearch XML (and AC will have to follow to some degree) we may want to find a solution that is independent from the XML implementation we have currently.

**Comment by liuche** [comment]
Closing this since we used the first suggestion.
