### ISSUE TITLE
Feature Downloads should provide a way to indicate if a dialog should be shown

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#2325]
Related issue https://github.com/mozilla-mobile/fenix/issues/952

**Comment by pocmo** [comment]
I wouldn't change the download behavior: I used the "download shortcut" since that already existed. If we do not want to go through that then we may just change the implementation of the context menu item: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt#L141-L155

**Comment by Amejia481** [comment]
Thanks for the clarification 👍
