### ISSUE TITLE
Add support for searchDefault field in list.json

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2371]
`list.json` now has a `searchDefault` field. Let's add support to that to our `SearchEngineManager`.

https://searchfox.org/mozilla-central/source/mobile/android/components/search/searchplugins/list.json

**Comment by jhugman** [comment]
Our current version of `list.json` hardly uses `searchDefault`.

Current version of Fennec does, though: 

 a) it's not clear if there are any other substantive but non-breaking changes to the format since last imported.
 b) the desktop version does have substantive changes.

Given #1719 allows for sharing a `list.json` parser between desktop and a-c (via WebExtensions), I'd suggest that we shouldn't update the kotlin parser to do more than necessary. 

Pinging @mkaply to check if importing latest fennec `searchplugins` and `list.json` would be useful/possible.

**Comment by mkaply** [comment]
I think you should go with the latest and use searchDefault for now. Unless you think that #1719 will happen fairly soon. I think for some period of time, Fenix will use xml and Desktop will use WebExtensions.

The only other change to the format was to add searchOrder to determine the order of search engines.

**Comment by jhugman** [comment]
Thanks, @mkaply
