### ISSUE TITLE
Mobile Activation Ping telemetry sender

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/android-components#2397]
Fennec telemetry shows 25% more installs than the Google Play Store does (bug 1483927). @fbertsch has specified a new Mobile Activation Ping (in bug 1501822) that includes a hash of the user's Google Ad ID in install/uninstall telemetry to count unique users and avoid double-counting reinstalls.

We want this new Mobile Activation Ping for Fennec (bug 1534451), Fenix (mozilla-mobile/fenix#1028), and other Mozilla apps. Thus, we should probably implement it in an A-C component that Fenix can call and Fennec can copy/paste (assuming Fennec doesn't use A-C components).

fbertsch recommends that We use A-C's Glean component. We can then use the "Ping Format" section of the Mobile Activation Ping spec as a guideline for which metrics to implement.

Fenix Mobile Activation Ping spec:
https://docs.google.com/document/d/1mYklPkL1LYnAnjfeyaiqXJ4uuui8r08GCgN30Iod53k/edit

Google Ad ID can be reset by users. Google's policy requirement is that all apps use this ID in lieu of any others for advertising. We are not using this for advertising so that policy should not apply to us.

**Comment by pocmo** [comment]
CC: @Dexterp37 @mdboom @travis79 @georgf

**Comment by georgf** [comment]
From our end we'll need to schedule work related after the current milestones.
This looks like somewhere in the second half of April is realistic.

Open questions:
- @cpeterso Should we support someone to implement or is the ask on us?
- For us: Should this be a component using Glean? Or a (optional) part of Glean?

**Comment by georgf** [comment]
I [mirrored this in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1538011) for our tracking.

**Comment by liuche** [comment]
Commented in PR #1707 but also here:
Is Mobile Activation Ping something that will be restricted in who can use it? I'm concerned that including this in Glean makes it seem like this is telemetry that is "approved for inclusion" by any consumer apps, but in this case, the GAID activation ping should *only* be used with approval.
Maybe the thing to do here though is to add this warning/caveat in the usage docs.

**Comment by Dexterp37** [comment]
> 
> 
> Commented in [PR](https://github.com/mozilla-mobile/fenix/pull/1707) but also here:
> Is Mobile Activation Ping something that will be restricted in who can use it? I'm concerned that including this in Glean makes it seem like this is telemetry that is "approved for inclusion" by any consumer apps, but in this case, the GAID activation ping should _only_ be used with approval.

This ping is currently not being implemented in Glean, but rather implemented in the Fenix repository (the PR you saw) using the Glean API. Due to this, I think that "who can use it" is implicitly "only Fenix". If any other product powered by Glean wanted to use this implementation, we would have to create a shared module in Android Components and make it clear that this requires data-review *every time*. We're working on a [Glean custom pings metadata](https://docs.google.com/document/d/1Dtqt2o7FC6SZ-vMrMBVe6HJdh0M26Hg3rIC9hfxn-40/edit#) proposal to make it easier for us to be explicit about expectations there (e.g. we can require a data-review for pings too and fail at build time if we don't have one).

**Comment by travis79** [comment]
Closing this since the mobile Activation pings are implemented and there is nothing more for Glean to do.
