### ISSUE TITLE
Allow a flag for NOT sending crash reports with Prompt.ONLY_NATIVE_CRASH

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#2551]
Currently, if you have `Prompt.ONLY_NATIVE_CRASH` set, all non-native crashes will be sent. In Fenix, we want the ability to show native crash prompt, but not send all non-native crash reports if the user toggles a setting.

**Comment by pocmo** [comment]
@sblatz So if the user disables the crash reporter we will still show the prompt?

**Comment by sblatz** [comment]
@pocmo We want the user to see the page below even when the crash _reporting_ is disabled, as otherwise the page just goes to about:blank without any explanation. Because of this, we have to `install` crashreporter even if the user has `sendCrashReports` disabled. This causes an issue when non-fatal crashes happen, as crash reports are still sent (or asked to be sent).

Does that clarify things?

<img width=300 src=https://user-images.githubusercontent.com/4400286/55173820-99fd2280-5139-11e9-8829-7ba287e35da7.png>

**Comment by pocmo** [comment]
@sblatz Some time ago we added some code that internally re-creates the gecko engine session if it crashed. However we do not reload or restore automatically in this situation. I wonder if that is the white screen you are seeing. I wonder if we should do more - or allow more?

Related: I wonder how you match crashes to the tab - afaik there's nothing in the lib for that - is that possible?

> Does that clarify things?

Yeah, that makes sense.

**Comment by sblatz** [comment]
@pocmo yeah, I've been looking into the "restoring" stuff a bit. So far my investigation has led me to [these findings](https://github.com/mozilla-mobile/fenix/issues/1002#issuecomment-473970666). 

It'd be great if this behavior was different, but I believe that this is a fix that requires GV changes. For now, I'm actually removing the "reload tab" button until this functionality is added.

**Comment by pocmo** [comment]
@sblatz I think we can already recover (but some AC work is needed). The reason that you are seeing `about:blank` is that under the hood we already create a new GeckoSession:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L443-L446

However we do not restore the state or load any page which is why it just points to `about:blank`. IN addition to that we do not tell the GeckoView about the new session which causes it to just "freeze" up because it still tries to render the crashed session.

I think for the full picture we would need to:
* Expose on the `Session` if it is crashed: I assume right now you do not even know which session crashed? It doesn't have to be the selected one - that's only always the case if you test with `about:crashcontent` :)
* Add an action/usecase that allows you to recover from a crash - where we'll re-inject the last state we know about into the new gecko session.
* Internally we need to tell the view if the currently rendered session crashed and we internally created a new one.

Does this make sense? Of course all of this is out of the scope of this bug and I would go ahead and file more issues and may even start working on them.

**Comment by sblatz** [comment]
We actually don't need this as we decided to use a checkbox again instead.
