### ISSUE TITLE
HistoryStorage: Provide a paged API

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#2644]

**Comment by pocmo** [comment]
Adding "AS dependent" label since I assume we would need an API that allows paging. It looks like currently we can only query for time ranges.

@boek Do you have any specific requirements here? What would be the ideal API for you? A `PagedList` / `DataSource` like in SessionBundleStorage? ([paging library](https://developer.android.com/topic/libraries/architecture/paging))

**Comment by boek** [comment]
@pocmo I think that would be ideal :) Adding sync caused history to load more than 40k items in some cases

**Comment by pocmo** [comment]
@boek Regarding priorities: This is needed for MVP, right?

**Comment by boek** [comment]
@pocmo Oh yes, definitely! Let me know if there is any way that I can help :+1:

**Comment by pocmo** [comment]
Filed AS issue to start a discussion on the lower-level APIs needed to support this:
https://github.com/mozilla/application-services/issues/992

**Comment by pocmo** [comment]
^ FYI @grigoryk

**Comment by thomcc** [comment]
Went out in https://github.com/mozilla/application-services/releases/tag/v0.26.0, usable once https://bugzilla.mozilla.org/show_bug.cgi?id=1545289 is completed.

**Comment by grigoryk** [comment]
This is done.
