### ISSUE TITLE
[Toolbar] Impossible to update Toolbar.ActionToggleButton selected state without calling listener

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#267]
Currently, I have:
```kotlin
        val pinButton = Toolbar.ActionToggleButton(...
                visible = toolbarStateProvider::isPinEnabled) { isSelected ->
            // This method will pin/unpin a site in the DB and show a toast
            onToolbarEvent(PIN_ACTION, if (isSelected) NavigationEvent.VAL_CHECKED else NavigationEvent.VAL_UNCHECKED)
```

I want to update `pinButton`'s selected state based url updates, which shouldn't write to the DB or show a toast. My only option to programmatically change the state is `toggle()`, which calls pin button's listener.

This could be fixed with #264, if it was a function: `fun setSelected(callListener: Boolean = false)`.

**Comment by pocmo** [comment]
I was hoping to copy the behavior of CompoundButton and derivatives (CheckBox, RadioButton, ..). But it turns out they have exactly the same problem, toggle() and setChecked() will call the listener. Solutions on Stackoverflow suggest to unset the listener temporarily to set the value. But that's ridiculous. Adding a dedicated method that accepts an additional flag may be the best solution here.
