### ISSUE TITLE
Unable to trigger Safebrowsing (high risk) errors in Reference Browser / Fenix

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#2725]
When I visit websites in Reference Browser or in Fenix that **should** trigger safebrowsing errors (e.g. Safebrowsing Phishing URI), the error is not intercepted. All medium / low risk errors are caught.

@jonalmeida confirmed this works correctly in sample browser.

**Comment by jonalmeida** [comment]
This is the test website: https://testsafebrowsing.appspot.com/

**Comment by Amejia481** [comment]
It looks like there is an issue with tracking protection, as I soon as I disable TC, I'm able to see the Safebrowsing pages (The same can be seen on  sample browser). I will keep researching: 

[Core.kt](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/Core.kt)
```kotlin
    val engine: Engine by lazy {
        val defaultSettings = DefaultSettings(
            requestInterceptor = AppRequestInterceptor(context),
            remoteDebuggingEnabled = Settings.getInstance(context).isRemoteDebuggingEnabled,
            testingModeEnabled = false,
           // trackingProtectionPolicy = createTrackingProtectionPolicy(),
            historyTrackingDelegate = HistoryDelegate(historyStorage),
            preferredColorScheme = getPreferredColorScheme()
        )

        GeckoEngine(context, defaultSettings, runtime)
    }
```

and 
[AppRequestInterceptor.kt](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt)
 
```kotlin
   override fun onLoadRequest(session: EngineSession, uri: String): RequestInterceptor.InterceptionResponse? {
        //adjustTrackingProtection(uri, context, session)
        // Accounts uses interception to check for a "success URL" in the sign-in flow to finalize authentication.
        return context.components.services.accountsAuthFeature.interceptor.onLoadRequest(session, uri)
    }
```

 
![Screenshot_20190515-152114](https://user-images.githubusercontent.com/773158/57807436-2fc33000-772f-11e9-84f2-6d947bb58ac5.png)

**Comment by pocmo** [comment]
@Amejia481 Oh, this almost sounds like a GV bug. Is that reproducible in GeckoView example?

**Comment by Amejia481** [comment]
Yes it a GV isssue, I'm documenting it. In GeckoView Example they are [setting TC](https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/GeckoViewActivity.java#178). For this reason none of the pages on https://testsafebrowsing.appspot.com/ trigger safe browsing error pages.

I could simulate the same on Sample Browser as soon as a set TC either to false or true I don't receive more safe browsing error pages.

**Comment by Amejia481** [comment]
I noticed that this our issue. We are not providing safe browsing categories in [TrackingProtectionPolicy](https://github.com/mozilla-mobile/android-components/blob/8ecfb1c0ae512a93c234621618c4f0ac89f3261a/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt#L83) for:

- [SAFE_BROWSING_MALWARE](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/ContentBlocking.java#280)
- [SAFE_BROWSING_UNWANTED](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/ContentBlocking.java#285)
- [SAFE_BROWSING_HARMFUL](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/ContentBlocking.java#290)
- [SAFE_BROWSING_PHISHING](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/ContentBlocking.java#295)
- [SAFE_BROWSING_ALL](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/ContentBlocking.java#301)

By default, `geckoRuntime` has it, but change the tracking protection policy, we don't add it back, for this reason the safe browsing errors works on Sample Browser but not Fenix, because on Sample Browser we don't apply any tracking protection policies but in Fenix we have.

**Comment by csadilek** [comment]
Good catch, @Amejia481. I was just wondering how that happened. Seems like the safe browsing categories were introduced after our `TrackingProtectionPolicy` and at the same time the generic AT_ALL was removed from GeckoView, so that's why our tests can't catch that.
