### ISSUE TITLE
SPIKE: Support Android Intent URLs

### ISSUE THREAD

**Issue by bifleming** [mozilla-mobile/android-components#2936]
**Timebox to 2 Hours

Deliverables:

- Determine effort for this work

- Identify whether the work can be broken down into multiple stories

- Provide implementation details**

--------------------------------------------------------------------------

The Android Intent URL spec lets web pages open Android apps. afaict, this is not currently built into components (ag browser_fallback_url) nor do the products handle such a case. If so, this regresses existing Focus and Fire TV functionality). This functionality is also supported in Fennec.

Fennec's behavior was roughly the following:

    Try to open app for intent. Prompt user first that they may be leaving the app.
    If there is no app, try to load the provided fallback URL, if relevant
    If there is no fallback URL, try to open the app on the market if relevant (note: some devices do not have the Play Store or other market so don't assume they do)
    If it fails, handle the link such that no action occurs (i.e. no error page is shown). Chrome has this behavior and many sites rely on it (see fennec code for details) such as clicking Facebook messenger links

See the old Focus, or Fennec, implementations for details. This behavior may be outdated and we may want to reaudit (e.g. is searching the store the best behavior?).

Test pages:

    m.facebook.com (click messenger)

**Comment by jhugman** [comment]
From a UI p.o.v.: 

Focus and Fennec both offer menu items and page actions (respectively) to open the app version of the page once the page has loaded. This is relying on [`PackageManager.queryIntentActivities`][android-queryIntentActivities]. Some effort goes to make sure that the activity is `exportable`.

It's not clear why we don't test the link on a `window.location` change, and offer to open the link in our browser (and thus increasing the potential that the user will set the browser as default) for every link.

Other pages, e.g. https://mobile.twitter.com, https://soundcloud.com, https://reddit.com offer [app-launch banners][docs] with a scheme and potentially a link to the market place and a fallback URL.

* Checks to see if it's a URL scheme that Fennec can handle — do so here.
* If not, then [parses the `custom://` URLs based upon schemes only and checks it against the OS scheme handlers][fennec-ask]
* if not, then [fallbacks if no app deals with that scheme][fennec-noHandler], either by going to the market place or a fallback URL supplied in the URL.
 * Finally, checking the time since last user interation (as a proxy for whether the user clicked on the link), then fail silently or display an unknown protocol error.

[docs]: https://developer.chrome.com/multidevice/android/intents
[fennec-ask]: https://dxr.mozilla.org/mozilla-central/source/mobile/android/components/ContentDispatchChooser.js#51
[fennec-noHandler]: https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/IntentHelper.java#491
[android-queryIntentActivities]: https://developer.android.com/reference/kotlin/android/content/pm/PackageManager.html#queryIntentActivities(android.content.Intent,%20int)

**Comment by jhugman** [comment]
Breakdown into stories: 

 * Implement API for opening web pages into `OpenPageInApp`, to handle unusual URL protocols on window location change
  - UI for needs some product/design decisions. Should we warn the user that the app or play store is going to be launched? If there is a choice of app, should we make our own dialog or should we rely on the system one.
 * Add API for session observers to observe if the session's URL can be opened by a native app (this is more generic intent filtering, not just `custom://` protocols.
   - Ensure that we're filtering out generic browsers from this list.
   - Add API/UI for choosing the app to open from a filtered list of apps.

Level of effort: 3 x M

**Comment by jhugman** [comment]
Opened #2974, #2975 #2976
