### ISSUE TITLE
Automate Nightly GeckoView dependency update

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#314]
Background:
* We want to track the latest Nightly version of GeckoView as much as possible
* We do not want to use version wildcards because then builds break randomly when the GV APIs change. We still want to pin a specific version that is known to work.

Could we write a script that:
* Determines the latest nightly version from taskclusters index service.
* Updates the build.gradle file (or another to-be-created file where we define the versions)
* Builds the components to see if everything still works
* If build successful: Opens a PR with the changes
* If build fails: Opens an issue linking to the failure so that we can update (and fix) manually

**Comment by pocmo** [comment]
Moving this into the next sprint to discuss: I would like to update Nightly more often than 0-1x a week.

**Comment by Amejia481** [comment]
I have made so cool progress with this feature but there're some things that are not completely clear to me.

- Where is this Gradle plugin going to run?
   To create pull request, first I have so create a branch then commit and push it GitHub.
   Depending if the plugin is going to be running on CI by a cron job or by a user after some timelap.

**Comment by Amejia481** [comment]
I have made so cool :) progress with this feature but there're some things that are not completely clear to me.

**Where is this Gradle plugin going to run?**
To create a pull request, first I have to use Git to  `create a new branch from master`,  
then `commit the changes` and `push it` GitHub.

Depending if the plugin is going to be running on CI by a cron job(or similar) or by a user after some time-lap. There're some conditions that I have to take into consideration.

For instance, if it runs by a user, there are some corner case like what about if this user has some changes apart from the changes made by the plugin updating the version? Should I commit them too?

If it runs by a cron job, there're fewer considerations to take, because it going to be a controlled environment.

**Comment by pocmo** [comment]
This will run on taskcluster (triggered by a [hook](https://tools.taskcluster.net/hooks/)).

As an example see how Focus imports strings (This will open a PR too):
* https://github.com/mozilla-mobile/focus-android/blob/master/tools/taskcluster/import_strings_and_create_pull_request.sh
* https://github.com/mozilla-mobile/focus-android/blob/master/tools/taskcluster/create-pull-request.py

**Comment by pocmo** [comment]
Also let's only update if the major version is the same:
* 64.x -> 64.y (OK)
* 64.x -> 65.y (Nope!)

**Comment by Amejia481** [comment]
👍
