### ISSUE TITLE
Move MessageBus to a support component

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3171]
The MessageBus is abstract enough to be put in a re-usable support component. We left in the push component until we found a good home for it that doesn't just bloat the `support-base` component.

**Comment by dector** [comment]
I'm just wondering if we need to spread custom implementation for `Bus` as there are other ways to achieve same functionality with Rx, Kotlin channels etc?

**Comment by jonalmeida** [comment]
There's definitely room for discussion here, however the `Bus` API/`MessageBus` built on top of the existing `ObserverRegistry`.

Rx would be an opinionated implementation that we don't want to enforce on consuming apps. Maybe Kotlin channels could work, but I'm not sure if it would solve the problem of multiple observers for a single message type.

**Comment by dector** [comment]
Yeah I meant that from architecture point of view global event-bus-like components are considered as ones that have quite limited usage because of their error-prone nature.

And I see that it indeed has limited usage in `AutoPushFeature`. My point here is that we should avoid exposing `MessageBus`. And prefer problem-specific interfaces with limited semantics instead..

I totally agree that implementation details (e.g. Rx) shouldn't be leaked through public interface. Seems that [`Flow`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/) is great candidate (experimental now).

**Comment by jonalmeida** [comment]
In https://github.com/mozilla-mobile/android-components/pull/5658 we've removed this feature since it's no longer used.
