### ISSUE TITLE
Display menu builder menu from bottom

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3211]
For [this fenix issue](https://github.com/mozilla-mobile/fenix/issues/2219).

We'd like to display the menu builder from the bottom so our most critical menu items are shown even when the whole menu can't be.

**Comment by Amejia481** [comment]
@sblatz is this issue the same as https://github.com/mozilla-mobile/android-components/issues/2916?

**Comment by sblatz** [comment]
@Amejia481 No, for this issue we're talking about starting the recylcerview of the menu builder from the bottom. For example, if my device is really short, we want to display C before B in the following menu:
A
B
C

**Comment by Amejia481** [comment]
@sblatz   Do you want to mark some `BrowserMenuItem` as important to let us know that they should be visible always even though that means moving them up in the list order?

**Comment by Amejia481** [comment]
Could scroll until the important items are visible could be enough?

**Comment by bifleming** [comment]
@vesta0 ^^

**Comment by vesta0** [comment]
@Amejia481 

Current state:
![Screenshot_20190606-170223](https://user-images.githubusercontent.com/42752644/59066622-7bc04b00-887d-11e9-95ff-a99adb9e72df.png)


Ideal state (so back/forward/refresh is visible):
![Screenshot_20190606-170230](https://user-images.githubusercontent.com/42752644/59066656-8aa6fd80-887d-11e9-8171-da297b1960f7.png)

**Comment by vesta0** [comment]
Ideally, we also want to have an arrow or something indicating that user can scroll up for more options. @mheubusch for post-mvp.

**Comment by pocmo** [comment]
@Amejia481 I assume this translates to: For preferred UP direction we scroll all the way down and for preferred DOWN direction we scroll up all the way (or do nothing because that's the default)

**Comment by Amejia481** [comment]
Just to confirm: @pocmo are you suggesting: 

1. Just using the actual [orientation property ](https://github.com/mozilla-mobile/android-components/blob/0529eb651713a60f1d2eb2b17467610fbe978298/components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt#L96) to do a scroll in the opposite direction (**UP** -> Scroll down and **DOWN** -> Scroll **UP**)

2. Adding a new property for the consumer to indicate which portion of the menu should be always visible when showing.

If option **1** is the preferred.  Is this mixing two concepts? **The orientation of the menu** and  **the direction that are we going to do scroll if there is not enough space show all the items?** Is this the expected behavior outside of the toolbar menu use case?

**Comment by pocmo** [comment]
I was suggestion (1), but yes, I primarily looked at the toolbar and the reference screenshots. For menus in a list like bookmarks that may not be the case and you may always want to show them top to bottom like we do right now.

**Comment by Amejia481** [comment]
As mentioned on https://github.com/mozilla-mobile/fenix/issues/2219#issuecomment-501666839 this is not working properly on Android 5 & 6 devices, let's take a look.

**Comment by vesta0** [comment]
I am removing MVP blocker since it's only impacting Android 4 & 6.
