### ISSUE TITLE
Set max text size for url text and title text

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3213]
For Fenix issues:
* https://github.com/mozilla-mobile/fenix/issues/1905
* https://github.com/mozilla-mobile/fenix/issues/2292

**Comment by sblatz** [comment]
I tried working on this with @csadilek for a while, but we had issues. It'd be great if someone else could pick up this ticket as it's blocking two Fenix issues.

**Comment by jonalmeida** [comment]
This is a day or two of debugging to figure out why the font resize is focusing on the end (this may be related to our custom `onLayout` and `onMeasure` that doesn't work with TextViews.

I also wasn't able to reproduce this on my device since (as mentioned) it seems more specific to Samsung devices.
