### ISSUE TITLE
When opening an external link, pressing back should close the tab (but not if user has navigated)

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3257]
See Fenix issue: https://github.com/mozilla-mobile/fenix/issues/2110

My comment
> I've addressed the closing of a session with source ACTION_VIEW in PR https://github.com/mozilla-mobile/fenix/pull/2953 but I'm not sure how best to deal with "if user has navigated in the session, save the tab". I had an idea to remove the ACTION_VIEW source in onUrlChanged (if the session canGoBack as well), but it looks like I can't change the source of the session. This may require further AC work for this portion.

It seems like we will at least need to be able to change the source as described above, but it's possible this entire interaction should be handled by the `SessionFeature` `onBackPressed()`?

**Comment by pocmo** [comment]
This is how we have implemented it in Reference Browser too.

And this is in parity with Fennec:
https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/GeckoApp.java#2383-2395

Fennec also never clears the "external" flag:
https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/Tab.java#70-72

When navigating the tab is retained on the next back press(es) since `SessionFeature.onBackPressed()` should navigate back in the Session's history. The last back will still close the tab and that's how Fennec seems to do this too. I think there's nothing additionally to be done here.

**Comment by ekager** [comment]
Okay, I'll close this then, thanks!
