### ISSUE TITLE
Crash reporter: Allow including page address

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3260]
Fennec allows users to attach the page address to crash reports.

That has been a helpful feature for debugging Gecko(View) crashes:
https://bugzilla.mozilla.org/show_bug.cgi?id=1555108

![image](https://user-images.githubusercontent.com/89638/58954667-1f382f80-879a-11e9-90ee-4141086dee67.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2648)

**Comment by jamienicol** [comment]
Has there been any decision not to implement this, or has it just never been prioritized? 

I ask because the lack of urls and comments on crash reports makes it next to impossible for me to reproduce graphics driver crashes. Combine this with the low nightly and beta populations which means we won't get a bug report with steps to reproduce until a crash reaches release (if even then).

The nightly population is a harder problem to solve, but submitting crash urls would make my life a lot easier :)

**Comment by pocmo** [comment]
It hasn't been prioritized high enough so far.

CC @rocketsroger

**Comment by jamienicol** [comment]
Has this been implemented?

**Comment by rocketsroger** [comment]
No, something wrong with data sync with JIRA.  Reopening.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792916

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
