### ISSUE TITLE
SessionManager: restore and intent processor race condition - tab added randomly at start/end of list.

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3432]
It'd be great if we had timestamps on session creation (or most recently used) so we could sort them accordingly in Fenix.

Would help us address: https://github.com/mozilla-mobile/fenix/issues/3346

@jonalmeida and I chatted about this and he has more info :)

**Comment by jonalmeida** [comment]
To clarify the current use case, when a session restore is taking place asynchronously, opening a new session from a cold boot puts the session at the top of the list of session and then follows with the restored tabs. This list is presented in a reverse order so puts the new session at the end of the collections list.

**Comment by pocmo** [comment]
It may be time to get UX back into this. Fenix has already diverged on how browsers traditionally sort tabs. Changing the order will fix the linked issue but very likely break other situations (e.g. child tabs opened next to their parent). We should look at those use cases and scenarios and define the behavior together with the UX team. AC currently just uses the same behavior as our other and third-party browsers.

That said, there's definitely an issue here with concurrent restore and incoming intent. And that's something we should fix - and that will fix https://github.com/mozilla-mobile/fenix/issues/3346 too without having to reorder.

**Comment by pocmo** [comment]
Two potential solutions I can think of:
* Delaying adding a `Session` coming from an Intent after restore has happened (Makes loading that tab slower though?)
* Adding restored tabs to the beginning of the list (as if they were restored first, shouldn't regress loading the incoming tab).

**Comment by sblatz** [comment]
I think your second solution sounds reasonable. Will that cause sorting issues when we use the "open collection" feature (which will restore previous sessions with unique ID's)?

**Comment by pocmo** [comment]
Yes, it will. Either we add a flag for this behavior - or change the way how we add tabs from a collection (a new "add multiple tabs" API vs. "restore") - which may make sense since we do not "restore" anymore but create new sessions (ids) now.

**Comment by pocmo** [comment]
@sblatz I implemented the following changes:
*  LANDED: (browser-session)`SessionManager.restore()` will always add tabs at the beginning of the list so that restoring can happen asynchronously / concurrently and it will always look like those tabs were the first.
* IN REVIEW: (feature-tab-collections) `Tab.restore()` now returns a `Session` (instead of a `Snapshot`) and `TabCollection.restore()/restoreSubset()` now returns a `List<Session>` (instead of a `Snapshot`)
* IN REVIEW: (browser-session): Added `SessionManager.add(List<Session>)` to add a list of `Session`s (at the end).

So in Fenix we will need to update the code to deal with a `Session` or `List<Session>` and pass that to `SessionManager.add()` instead of `SessionManager.restore()`. Sounds good?
