### ISSUE TITLE
Downloaded images from Twitter or Google Images save with .bin format

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3516]
Copied from: https://github.com/mozilla-mobile/fenix/issues/3624

Also see: https://github.com/mozilla-mobile/fenix/issues/2809

Same bug in Focus that a contributor tried to fix IIRC: 
https://github.com/mozilla-mobile/focus-android/issues/2743

---------------

## Steps to reproduce
1. Go to twitter.com
2. Long tap on an image and save image.

### Expected behavior
The image has a .jpg file format.

### Actual behavior
The image has a .bin file format. A saved image from Wikipedia articles is saved with .jpg file format.

### Device information
* Android device: ?
* Fenix version: 1.0.1926 (#11750611)

### Note
Bug filed from https://github.com/webcompat/web-bugs/issues/33424

**Comment by Amejia481** [comment]
The issue here is that on some images on Twitter, we're not getting the file extension as part of the end of the `URL`, it is been passed as a parameter of the query string `https://pbs.twimg.com/media/D964pzzX4AASSIz?format=jpg&name=4096x4096`. For those edge cases, we could to perform an HTTP HEAD request on the `URL` to figure out the mime type. 

This could add extra overhead to what we are doing now, an optimal solution is to wait for the [Gecko-based DownloadManager](https://github.com/mozilla-mobile/android-components/issues/1968) and #1968 add the file extension when we have downloaded the file.

Depends on: https://github.com/mozilla-mobile/android-components/issues/1968

**Comment by ekager** [comment]
Came here to bump this because someone reached out that this is their number one annoyance but see that @NotWoods is already making commits 🙌 😆
