### ISSUE TITLE
Update artifact names of concept modules

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#368]
From #364:

> We have some inconsistency here now:
> 
> concept-toolbar -> abstract-toolbar
> concept-engine -> engine
> concept-tabstray -> concept-tabstray

When switching from jcenter to our own repository there's an opportunity to update our artifact names.

**Comment by pocmo** [comment]
The concept modules are only one inconsistency. A different one is that we drop the "prefix" we use in our gradle and module structure:

browser-toolbar -> org.mozilla.components:toolbar
concept-toolbar -> ...?

We kind of noticed that when we introduced feature modules, because:

feature-toolbar -> org.mozilla.components:feature-toolbar

I think it would be nice if the gradle module (e.g. feature-toolbar, concept-toolbar, browser-toolbar) would be the artifact name too. With that it's also easier to *guess* the artifact without needing to look it up (You want to use browser-toolbar? Okay, then import org.mozilla.components:browser-toolbar).

Another thing to re-consider some of our ui-components:
ui-colors -> org.mozilla.**photon**:colors
ui-icons -> org.mozilla.**photon**:icons
ui-progress -> org.mozilla.**photon**:progress

But:
ui-autocomplete -> org.mozilla.**components**:autocomplete
ui-tabcounter -> org.mozilla.**components**:tabcounter

**Comment by csadilek** [comment]
+1. I think we should go with these changes:
- Add the prefix to all artifacts (browser-toolbar, ui-autocomplete). Should we add it to the groupId or artifact name? `org.mozilla.components.browser.toolbar` or `org.mozilla.components.browser-toolbar`. The latter (a flat namespace) seems better to me. Wdyt?
- Rename `org.mozilla.photon` to `org.mozilla.components`
- Let's use `concept` not `abstract` to keep artifacts and project names consistent?

**Comment by pocmo** [comment]
@JohanLorenzo @MihaiTabara I saw that you made good progress with the deployment to maven.mozilla.org. Do you think it would be possible to use different group Ids / artifact Ids for this setup? The switch to the new maven repository would be a good time for the update.

**Comment by pocmo** [comment]
> Add the prefix to all artifacts (browser-toolbar, ui-autocomplete). Should we add it to the groupId or artifact name? org.mozilla.components.browser.toolbar or org.mozilla.components.browser-toolbar. The latter (a flat namespace) seems better to me. Wdyt?

I prefer the `org,mozilla.components:browser-toolbar` too. It's also a direct mapping of gradle module name to artifact name.

> Rename org.mozilla.photon to org.mozilla.components

+1

> Let's use concept not abstract to keep artifacts and project names consistent?

+1

**Comment by MihaiTabara** [comment]
Sure, we can definitely take these along, I was actually just working on that in https://github.com/mozilla-mobile/android-components/pull/803. Am hoping to publish a staging release by EOD and have the PR sent to @JohanLorenzo for initial review. We'll be able to glance at the artifacts better  and iterate once we have them published in the maven repo.

**Comment by MihaiTabara** [comment]
@pocmo @csadilek Just wanted to confirm that @JohanLorenzo and myself understood this right.
You want the artifacts to be published under this form:

1. `org.mozilla.components.lib-dataprotect.0.24....`
2. `org.mozilla.components.support-test.0.24....`
3. `org.mozilla.components.support-ktx.0.24....`
4. `org.mozilla.components.support-utils.0.24....`
5. `org.mozilla.components.support-base.0.24....`
6. `org.mozilla.components.concept-engine.0.24....`
7. `org.mozilla.components.concept-toolbar.0.24....`
8. `org.mozilla.components.concept-tabstray.0.24....`
9. `org.mozilla.components.browser-engine-gecko.0.24....`
10. `org.mozilla.components.browser-engine-gecko-beta.0.24....`
11. `org.mozilla.components.browser-engine-gecko-nightly.0.24....`
12. `org.mozilla.components.browser-engine-system.0.24....`
13. `org.mozilla.components.browser-session.0.24....`
14. `org.mozilla.components.browser-menu.0.24....`
15. `org.mozilla.components.browser-toolbar.0.24....`
16. `org.mozilla.components.browser-tabstray.0.24....`
17. `org.mozilla.components.browser-errorpages.0.24....`
18. `org.mozilla.components.browser-search.0.24....`
19. `org.mozilla.components.browser-domains.0.24....`
20. `org.mozilla.components.service-telemetry.0.24....`
21. `org.mozilla.components.service-sync-logins.0.24....`
22. `org.mozilla.components.service-fretboard.0.24....`
23. `org.mozilla.components.service-firefox-accounts.0.24....`
24. `org.mozilla.components.feature-tabs.0.24....`
25. `org.mozilla.components.feature-session.0.24....`
26. `org.mozilla.components.feature-toolbar.0.24....`
27. `org.mozilla.components.feature-search.0.24....`
28. `org.mozilla.components.ui-colors.0.24....`
29. `org.mozilla.components.ui-autocomplete.0.24....`
30. `org.mozilla.components.ui-icons.0.24....`
31. `org.mozilla.components.ui-fonts.0.24....`
32. `org.mozilla.components.ui-progress.0.24....`
33. `org.mozilla.components.ui-tabcounter.0.24....`

Where:

1.  `artifact-id` is similar with the gradle module name as well
2. `photon` no longer exists and all `ui` modules are under `components`
3. `abstract` is no longer needed since we're now using `concept` to differentiate from the other two existing `toolbar` 
4. All of them are prefixed with the `group-id`. 

Right?

**Comment by pocmo** [comment]
Okay, moving this out of our sprint @MihaiTabara and @JohanLorenzo will take care of this as part of our migration to maven.mozilla.org. This is great and we definitely want to avoid burning down jcenter with this change.

**Comment by MihaiTabara** [comment]
Tackled in https://github.com/mozilla-mobile/android-components/pull/803.
