### ISSUE TITLE
App links: detect links from the same domain as the current page, and suppress external app links

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#3691]
Certain web apps use top-left back buttons for navigation. Additionally, apps use links within the same webapp.

Using these internal links should not trigger an external app to be launched, especially if the user has already selected a browser to view the web app.

**Comment by softvision-miralobontiu** [comment]
I verified if this issue is fixed with the following STR:
1. Open Twitter in Firefox Preview and sign in.
2. Make sure Twitter app is installed on that device.
3. Navigate on Twitter in the browser and check if  "Open in App" from QAB is working.

Basically, I verified that the link I was on in Firefox Preview was the one opening in the external app, when "Open in App" is tapped.
Tested with the latest Nightly build 190731 (#12120612), with Google Pixel 3 (Android 9).
