### ISSUE TITLE
React to WebChannel extension events to notify the SyncManager

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#3817]
When the user select what to sync the Web-channel extension will be notified and we need to forward these event to the SyncManager.

**Comment by grigoryk** [comment]
General shape of the messages we'll receive from the WebExtension is described in #3826 (ticket that tracks the WE work itself). Expect to have at least "signIn", "signUp", "password changed" events.

**Comment by grigoryk** [comment]
Some `FxaAccountManager` public API changes that we'll need to make here:
- we will now receive a list of enabled engines during sign-ups. One way to model that is by adding an optional `enginesToSync` parameter to `finishAuthenticationAsync`
- "your password changed"/"account updated" public api method, that should change internal state of the `FirefoxAccount` object so that we continue to be able to issue valid access tokens. Additionally, it should repopulate `SyncAuthInfo` cache.
  - i'm assuming here that we'll get enough information from the WebExtension. In a similar situation, Fennec receives `[email, uid, verified, unwrapKB, sessionToken, keyFetchToken]`.

Additionally, consider if we can replace `request interceptor` logic entirely. This could be done at the `feature` level.

**Comment by rfk** [comment]
FWIW, I have some high-level advice here based on our experience implementing WebChannel message support in other browsers: trust, but validate. The web content has its own view of the world which may not match with your own, so always validate what it's asking you to do just in case it has gotten confused. For example:

* If you receive a message listing then enabled engines, make sure you're actually in the middle of a signup flow where such a message would be expected
* If you receive a "password changed" message, check that it's for the same account as the one you believe you're signed in as.

I think the explicit-state-machine approach used here will help make this easier.

**Comment by grigoryk** [comment]
WebChannel side of things done in https://github.com/mozilla-mobile/android-components/pull/4221
SyncManager integration is coming in https://github.com/mozilla-mobile/android-components/issues/2727, which will cover this issue.
