### ISSUE TITLE
Support Browser.EXTRA_HEADERS parameters

### ISSUE THREAD

**Issue by BugsBunnyBR** [mozilla-mobile/android-components#3832]
same as in here https://github.com/mozilla-mobile/focus-android/issues/4311

> ### Why/User Benefit/User Problem
> 
>     * Developers can use standard Android parameters to open the browser and deliver a better experience when Firefox is the default browser app keeping users session while in the native app and in the browser.
> 
> 
> ### What / Requirements
> 
>     * When opening the app, there is a need to check for the headers in the intent and forward it together with the url.
> 
> 
> ### Acceptance Criteria (how do I know when I’m done?)
> 
> When there is no other browser app installed/enabled in the phone and a request to `https://www.cylog.org/headers/` shows the custom headers.

**Comment by NotWoods** [comment]
We need a GeckoView API to load a URL with custom headers. This extra corresponds to `ACTION_VIEW`.

- [Android Docs reference](https://developer.android.com/reference/android/provider/Browser#EXTRA_HEADERS)
- [Sample usage](https://android.googlesource.com/platform/packages/apps/Browser/+/froyo/src/com/android/browser/BrowserActivity.java#652)

**Comment by NotWoods** [comment]
Filed [Bug 1567549](https://bugzilla.mozilla.org/show_bug.cgi?id=1567549)

**Comment by cpeterso** [comment]
This should be straightforward to implement because Gecko already has an custom header API we can expose in GV API. Does Chrome support EXTRA_HEADERS in custom tabs?

I've asked the Gecko content security team if there any security concerns about GeckoView including arbitrary HTTP request headers specified by a third-party app launching GeckoView in a custom tab.

**Comment by BugsBunnyBR** [comment]
Yes, Google Chrome supports `EXTRA_HEADERS`. Currently in the company app we need to use an internal webview when Google Chrome is not available, otherwise we just forward the headers to Google.

**Comment by cpeterso** [comment]
The GV bug has been fixed in GV 71 Nightly, which will ride to the GV Beta channel on October 21 unless Fenix or A-C needs it sooner.

https://bugzilla.mozilla.org/show_bug.cgi?id=1567549#c10

**Comment by st3fan** [comment]
@cpeterso were there no security concerns with this feature?

**Comment by cpeterso** [comment]
> I've asked the Gecko content security team if there any security concerns about GeckoView including arbitrary HTTP request headers specified by a third-party app launching GeckoView in a custom tab.

> @cpeterso were there no security concerns with this feature?

Redirecting question to @fluffyemily because I'm no longer working on GeckoView.

[I noted in bug 1567549](https://bugzilla.mozilla.org/show_bug.cgi?id=1567549#c6) that WebView's API docs says it won't allow apps to override default headers.

[Martin Thomson said](https://bugzilla.mozilla.org/show_bug.cgi?id=1567549#c13): we "should follow the processing rules for additional headers in fetch. For that, it needs to actually use the fetch code that enforces those restrictions rather than building parallel policy enforcement code. Otherwise, we're taking on a maintenance burden - and this might not get fixed when problems arise with fetch."

I don't know if GeckoView is using fetch's code to additional headers or not!

**Comment by BugsBunnyBR** [comment]
Thanks for this folks!
Would it be possible to know from what version of Firefox it will be supported?
