### ISSUE TITLE
Sample browser: Multiple BrowserFragment instances kept around while tabs are open

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3887]
When multiple tabs are opened then we see multiple `BrowserFragments` still being around. Once we close the tabs they go away. Often there's one additional last zombie `BrowserFragment` that stays around (2 Fragments and one tab).

A first investigation seems to point at the reader view feature. Without that feature the `BrowserFragment` count seems to stay at 1.

**Comment by csadilek** [comment]
The problem is caused by referencing the feature from within a content message handler: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt#L209

This will cause the feature to stick around for the lifetime of the gecko session i.e. as long as the tab is open the feature will be around too (and therefore the fragment).
