### ISSUE TITLE
Media notification pause/play button starts wrong video on sites with multiple MediaElements (that have autoplay?)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4115]
STR:
1. Go to a site with multiple video elements on it (example: https://shapeshed.com/examples/HTML5-video-element/)
2. Play a video in the list that is not-autoplayed.
3. Pause the video from the media notification.
4. Play the video from the media notification

## Expected
1. The media element of the paused video plays.

## Actual
1. The media element of another video (autoplay enabled video?) starts to play as well.

**Comment by pocmo** [comment]
What's happening here is that when pressing "play" we resume playing all paused media for that session. If you played and paused multiple (unrelated to autoplay, but more likely that this will happen) then we will resume ALL of them.

A solution may be:
* When transition from PLAYING to PAUSED then only copy Media over to the PAUSED state that was playing before (instead of collecting ALL paused media like we do currently).
* When pressing PLAY then resume playback of the media in the current state instead of looking for all paused media in the session.

**Comment by pocmo** [comment]
> A solution may be:

That works. But since we pause one video after the other this breaks when trying to pause and resume multiple videos in one atomic transaction. Maybe we can work around that with a lock.

**Comment by pocmo** [comment]
A lock does not help since we cannot lock over what happens in GV. The call to "pause()" completing does not mean the media is already paused and we have received that new state.

Only two other options I can think of at the moment:
* (1) Paused State Media = Media that was paused since the last Playing State. May work well - if no paused media appears without playing it.
* (2) Paused State Media = All recently paused media. If we switch from playing to pause then we collect all media that was paused in the last x seconds.

**Comment by pocmo** [comment]
A third (3) option is to delay/throttle updating the state for a short period of time until no more events come in. Then we automatically accumulate pause events. However that will delay updating the notification etc. too. So we should pick a short time.

**Comment by pocmo** [comment]
Option 3 works, is less code and does not require us to add anymore state. I'll do some more testing and put up a PR.
