### ISSUE TITLE
BrowserToolbar's ToolbarPresenter.initializeView() doesn't use the new session

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#4141]
Related to https://github.com/mozilla-mobile/fenix/issues/4768

BrowserToolbar's ToolbarPresenter registers an observer for the correct session, but instead uses the stale value of the Session in its constructor to initialize its View each time a session change occurs. This means that the toolbar view can remain stale even if the client explicitly calls `onSessionSelected(session)`. This can lead to some potentially serious UI edge cases for client browsers if the view isn't entirely recreated.

**Comment by jonalmeida** [comment]
This is a regression that was caused by the refactor of the BrowserFragment in Fenix where a [session is passed to the BrowserToolbar](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L185). What this tells the SessionManager and all features is "I'm giving you a session to observe, so don't change your selected session" hence the toolbar always focusing on the last selected session.

**Comment by colintheshots** [comment]
So what is supposed to happen in `ToolbarPresenter.onSessionSelected(session)` exactly? It starts observing the new session, but then initializes the view to the old session temporarily. What is the use case for that behavior?

**Comment by jonalmeida** [comment]
For the ticket: we've spoken on Slack about the details on passing in a sessionId for knowing a custom tab session vs selecting a specific session that stop observers for receiving `onSessionSelected` changes.
