### ISSUE TITLE
Username Cached after FxA is Disconnected

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#4236]
Android Component currently clearing the account storage when disconnecting.  However, the username is still remembered when turning the sync back on.

Something is still caching the username even though Android Component cleared it.

**Comment by shane-tomlinson** [comment]
@grigoryk - I'm a bit confused, is the problem that FxA continues to show the previously signed in user and just allows the user to enter their password to sign in again? If so, this is how desktop works too.

**Comment by sblatz** [comment]
I'm adding this to the AC triage as it's blocking a ticket we've had in Fenix's sprints for a few weeks: https://github.com/mozilla-mobile/fenix/issues/2833

**Comment by grigoryk** [comment]
@shane-tomlinson that's it, yeah. I believe this is how Fennec works as well. However, the Fenix team really wants a "disconnect" action to fully reset this state, so that the user sees a "enter your email" form instead. I tend to agree that it's a little weird to retain past user's information after they've disconnected.

**Comment by shane-tomlinson** [comment]
>  I tend to agree that it's a little weird to retain past user's information after they've disconnected.

The behavior is so that users can sign into non-Sync RPs w/o having to enter their email address.

**Comment by sblatz** [comment]
I think this is not high priority. It seems like it was moved out of the sprint backlog which I agree with :) 

Caching the email doesn't seem like obviously broken behavior, and there's been some back and forth on what we should even do here. I'm going to close this per our conversation in the AC/Fenix meeting, and if we feel it's truly broken we can talk to @vesta0 about expected behavior.
