### ISSUE TITLE
AccountObserver: differentiate between sign-in and sign-up 

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4238]
We'll need this for telemetry purposes.

Also: currently there's a flag - `newAccount` - which differentiates between "sign-in/sign-up and restore". That's a potentially misleading name, in retrospect. For example, due to a mistake Fenix treats it as a flag differentiating between "sign-in and sign-up". Let's rename that to `isRestore`, or similar.

**Comment by rfk** [comment]
From our previous discussion in slack, where I misunderstood you wanting this for Fenix instead of Fennec:

"""
when signing in to OAuth reliers on the web, we do appear to include an action=signin or action=signup query parameter to let them know whether it was a new or existing account; I wonder if Fenix also gets this today on the OAuth flow (edited) 
"""

So I expect that you already get this information from FxA at the completion of the OAuth flow.

**Comment by rfk** [comment]
What I mean is, you can probably get this information today in the OAuth redirect, without having to wait for thwe webchannel stuff to land. (Which may or may not be useful information, just wanted to note it explicitly).
