### ISSUE TITLE
Update copy and graphic on QR code scanning screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/android-components#4261]
Our reticle screen still needs updating using the fancy attached graphic made by @shorlander. We've also dropped the https for legibility (as it redirects to https anyway)
[reticle.zip](https://github.com/mozilla-mobile/android-components/files/3560022/reticle.zip)

<img width="371" alt="image" src="https://user-images.githubusercontent.com/68213/64023616-b34e3480-cb06-11e9-9146-a1d0f473d516.png">

**Comment by lime124** [comment]
@vesta0 no design work needed.

**Comment by lime124** [comment]
strike that - i hadn't realize this was in the A/C backlog

**Comment by drigio** [comment]
Hello @lime124 @ryanfeeley I would like to work on this if available.

**Comment by NotWoods** [comment]
@drigio If you comment on mozilla-mobile/fenix#6198 I can assign that to you too.

**Comment by sblatz** [comment]
In sprint planning we discussed that this is a lot of work due to testing on lots of different aspect ratios. The solution isn't hard, but that's why we're deferring for now.

**Comment by shorlander** [comment]
> In sprint planning we discussed that this is a lot of work due to testing on lots of different aspect ratios. The solution isn't hard, but that's why we're deferring for now.

@sblatz Is there a reason this would be more prone to error than any other piece of UI or even the current implementation of the QR code scanner?

Right now it's centered and if you happen to change the aspect ratio it scales to fit.

The reason I ask is because currently it's not in a good state. You can hardly see the black reticle in many situations and the instructions easily get lost pinned to the top of the view. We are funneling anyone who wants to sign-in to Sync to this slightly broken experience.

**Comment by liuche** [comment]
@NotWoods do you have any context on why this might be difficult? ^

**Comment by mcarare** [comment]
@liuche : After spending some time to investigate this, IMO implementing this will have a degree of risk, as we have to revert changes made in https://github.com/mozilla-mobile/android-components/pull/5985.  Or we could keep them, but we would still have a square preview, instead of the full display one like in the comment 0.

**Comment by liuche** [comment]
Interesting, how about we keep the "square" scan area from #5985, and overlay the black inside the square? I think the important part of this issue is that in the current QR scan implementation, the little window outline that shows where to align the QR code is hard to see.

Can you add the black alpha overlay from the mock to create the "scan window" but keep the square cut?

**Comment by csadilek** [comment]
Fixed by: https://github.com/mozilla-mobile/android-components/pull/6939

**Comment by liuche** [comment]
Thank you @mcarare! @ryanfeeley take a look at the new Nightly Fenix :)
