### ISSUE TITLE
Tapping on the awesomebar during autocomplete fills url with history

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4328]
See [video](https://thumbs.gfycat.com/PreciousCarelessHeifer-mobile.mp4) as well.

### STR
1. Have a history items with a path (e.g. example.com/a/b/c and example.com/a/d/e)
2. Type into the awesomebar "examp".
3. Tap on the awesomebar to the right of the text that was filled.
4. Observe the text in the awesomebar in after each tap.

### Expected
 - Nothing should happen.

### Actual
 - The toolbar fills with text from history.

I can reproduce this on Fenix and R-B.

**Comment by jonalmeida** [comment]
Nominating for sprint planning to get an idea what @vesta0 thinks about it's priority.

**Comment by ekager** [comment]
Just saw this and thought I would contribute some STR because this is very strange when it happens:
1. Perform some searches on hotels.com
2. In a new tab, load hotels.com
3. Click on search

Display Toolbar displays: "hotels.com"
Edit Toolbar displays: "hotels.com/search" with search highlighted strangely
Clicking on edit toolbar displays an even longer filled URL

![Screenshot_20200329-120847](https://user-images.githubusercontent.com/25442310/77858128-4bec8600-71b6-11ea-9730-1e1602a13e9b.png)
![Screenshot_20200329-120853](https://user-images.githubusercontent.com/25442310/77858127-4b53ef80-71b6-11ea-88fc-9a02e6156fd2.png)
![Screenshot_20200329-120907](https://user-images.githubusercontent.com/25442310/77858126-498a2c00-71b6-11ea-8428-01a1cde3fed7.png)

Clearing history seems to have stopped this

**Comment by ekager** [comment]
I've also seen this autocompleting the end of an entirely different host from history (not even the same webpage)

**Comment by jonalmeida** [comment]
Adding this to the a-c triage.

**Comment by grigoryk** [comment]
This seems like a feature to me? (maybe somewhat incomplete/unpolished, if it appears as a bug to ya'll).

I think Fennec did relatively well, IIRC - similarly autofilling chunks of the url path.

**Comment by jonalmeida** [comment]
I'm closing this as a duplicate of https://github.com/mozilla-mobile/android-components/issues/7043 after testing out the change in https://github.com/mozilla-mobile/android-components/pull/7058 which fixes this bug.

> This seems like a feature to me? (maybe somewhat incomplete/unpolished, if it appears as a bug to ya'll).
> 
> I think Fennec did relatively well, IIRC - similarly autofilling chunks of the url path.

The linked issue has a nice gif of what the bug is. I don't see the same behaviour on Fennec in a quick test there.
