### ISSUE TITLE
Add reader state to browser-state

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#4398]
We currently have two flags in browser session:
readerable - whether or not the current page can be shown in reader mode
readerMode - whether or not reader mode is on

We need to bring these to browser-state for https://github.com/mozilla-mobile/android-components/issues/4397.

Alternatively, we could look for a solution to let features extend browser-state and define their own actions/reducers. We never quite liked that these fields are added to the session directly, but it seems to be the easiest solution.

**Comment by pocmo** [comment]
I think with the nested structure in `browser-state` we can at least make this a bit nicer and keep feature state outside of the "content state". And we can create one rich object for the state of the feature (e.g. `ReaderModeState`) instead of having multiple fields in various places.

Something like:
- `SessioState.readerMode: ReaderModeState?`
- or `SessionState.features.ReaderModeState?`
- or if it doesn't affect custom tabs then only on `TabSessionState`?
