### ISSUE TITLE
Try other icons if downloaded icon is too small.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4495]
If we select the best icon candidate, download it and then determine that it is too small then we continue with no icon instead of trying to download the next candidate.

Also see: https://github.com/mozilla-mobile/fenix/issues/2964

**Comment by kbrosnan** [comment]
This seems to be the root cause of some common favicon issues in Fenix. I looked at a couple issues in Fenix where the favicon that is sent contains 64px, 32, px and 16px images.

**Comment by Amejia481** [comment]
@pocmo  I would like to confirm if the [default icon size](https://github.com/mozilla-mobile/android-components/blob/e655377b619d79a5c3d58adaec7d66fc66b53385/components/browser/icons/src/main/res/values/dimens.xml#L6) `32dp` was intentionally created in `dp` instead of `px` as I noticed that we are discarding many `32px` for being too small. 

From [AndroidImageDecoder.kt#L48 ](https://github.com/mozilla-mobile/android-components/blob/e655377b619d79a5c3d58adaec7d66fc66b53385/components/support/images/src/main/java/mozilla/components/support/images/decoder/AndroidImageDecoder.kt#L48):

```kotlin
// using play.google.com icon
// min(bounds.width, bounds.height) = 32 (px)
// maxScaleFactor = 2
// targetSize = (32dp to px  = 32dp * 2.75 my device density = 88
// Replacing all the values in the condition min(bounds.width, bounds.height) * maxScaleFactor < targetSize
// 32 (px) * 2 = 64  < 88 (targetSize) = false
min(bounds.width, bounds.height) * maxScaleFactor < targetSize -> {
    logger.debug("BitmapFactory returned too small bitmap")
    false
}
```

If above the `maxScaleFactor` get replace with device's density `2.75 `, the icon will be used as both the icon size and target size are in the same units.
`32 (px) * 2.75 = 88  < 88 (targetSize) = true`

**Should we use `32px` instead `32dp` as default icon size** ? As `dp` units are going to be always bigger than `px` as they get multiple by the device's screen density.

**Comment by pocmo** [comment]
Yes, I think this was on purpose to guarantee getting an icon that looks good at the size we usually display them in the UI. But I am not opposed to changing this value. However I wonder if we still would want to pick a `dp` size. Yes, this will mean the minimum size depends on the device, but on a device with a higher pixel density we may want to get a larger icon to make it look good?
32 pixels sounds very small. Did you try some of them in the UI? I wonder if they still look good?

**Comment by rocketsroger** [comment]
Amazon.ca is a different case.  It's not that we throw away the icon because it's too small.  A-C didn't get any icon resource in `MozacBrowserIcons` message event.

**Comment by pocmo** [comment]
@rocketsroger You solved _a_ problem, but I don't think the one I originally described here. Should we file a new bug for that?

**Comment by rocketsroger** [comment]
> @rocketsroger You solved _a_ problem, but I don't think the one I originally described here. Should we file a new bug for that?

I was assuming with https://github.com/mozilla-mobile/android-components/pull/10297 that this is fixed.  Should we keep this issue open?

**Comment by pocmo** [comment]
It lowered the minimum size, which may be good enough for now. But this doesn't prevent the original problem described in the first comment afaik:

> If we select the best icon candidate, download it and then determine that it is too small then we continue with no icon instead of trying to download the next candidate.

I am okay with just moving this to a new issue if there is no need for it right now.

**Comment by rocketsroger** [comment]
Sure, I'll open a new issue.  Thanks!

**Comment by rocketsroger** [comment]
Created. https://github.com/mozilla-mobile/android-components/issues/10377
