### ISSUE TITLE
Use the canonical URL when sharing a page

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4531]
Originally filed as mozilla-mobile/fenix#2769:
>### Why/User Benefit/User Problem
>Some URLs are needlessly long. They may occupy a whole screen on a chat app.
>
>### What/Requirements
>Cut non-crucial parts of URLs
>
>### Acceptance Criteria (how do I know when I’m done?)
>The feature is available on Chrome and ot is described here: >https://www.ghacks.net/2018/02/20/chrome-64-for-android-cuts-urls-automatically-when-you-share-them/

We can probably extract the URL using a web extension.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3831)

**Comment by jonalmeida** [comment]
I was just about to file an issue for this!

Since we have a `feature-share` component, we might be able to do this.

It would be nice if we also removed the query params in the components side if GV isn't able to provide us with the `canonical` URL - a simple list that stripped out `utm_*` params.

For example, sharing a link when we don't have a canonical URL:
```
https://www.wired.com/story/the-earth-is-flat?mbid=social_twitter&referer=twitter&utm_brand=wired&utm_campaign=wire&utm_medium=social&utm_social-type=owned&utm_source=twitter
```

Should result in the tracking params being removed:
```
https://www.wired.com/story/the-earth-is-flat?referer=twitter
```

**Comment by kbjarkefur** [comment]
I was coming here to see if there is any discussion on a feature like this already.

I always try to copy URLs without the tracking params, but modern URLs are too long for a mobile device screen. It would be awesome with a "copy URL" button where you can un-check the GET params that you do not want to include. 

And instead of being fully automatic, it could have a color code where the color indicate how much you reveal about your self. Red would be a tracking ID like `?fbid=1234567890qwertyuiop` and yellow for something that is not unique but says something about you `?referer=twitter` and green for anything that is part of what you want to share like a search term `?q=firefox`. Then undefined can be grey or have no color.

This would help people stay private on the internet when browsing websites that tries to track you when you share content.

**Comment by NotWoods** [comment]
In addition to the HTML `<meta>` tag, canonical links can be set as [a HTTP header](https://en.wikipedia.org/wiki/Canonical_link_element#HTTP). I'm not sure if there's any system for AC to extract headers from the initial HTTP request. If not, GeckoView needs to add support for that or handle canonical URL parsing internally.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794879

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
