### ISSUE TITLE
use two characters for website icon fallback

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/android-components#4533]
Currently Fenix uses the first character of the hostname as fallback image if Fenix can't find a suitable website icon. It's a nice idea but limited to 26 characters so it's of limited use to distinguish websites.

I propose to use the first characters to give more value to the fallback images. The idea is inspired by the popular (well, at least in Germany) CMS and community software WoltLab Suite (https://www.woltlab.com/?l=2) where the first two characters of the username are used as fallback image if the user doesn't upload an avatar.

<img width="650" alt="screen" src="https://user-images.githubusercontent.com/1100614/63211995-274c0e00-c0ff-11e9-9b5b-e4042da37dc0.png">

As you can see it's a very similar idea.

I think this would work great in Fenix as well. But this probably requires changing the library view a bit because the icons in the library are much smaller than in the tabs view. I don't understand anyway why there is a totally different icon style on the start screen and in the library so maybe it's a good opportunity to harmonize the website icon style across the product. ;-)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3834)

**Comment by NotWoods** [comment]
Transferring to Android Components because all the icon code lives here and Fenix wouldn't need any additional changes.

**Comment by topotropic** [comment]
Thanks for the feedback. It feels like there are quite a lot of history entries and bookmarks that don't have favicons because we introduced them a little later. Is there a way to retroactively fetch  favicons, at least for bookmarked sites, @NotWoods?

I understand that it would be nice to have a better indicator of what site is bookmarked when there's no favicon. I find your design suggestion interesting but I have the feeling that it's easier to do with names by using the initials or first two letters in case it's just one name then with URLs. I'm not convinced that this additional second letter makes a tremendous difference in helping to identify sites. We might also run into issues where the URL for example is "qz.com" but we would show "QU" which might be misleading.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793159

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
