### ISSUE TITLE
Drawable ripple issues in browser toolbar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#4673]
As seen in Fenix issue: https://github.com/mozilla-mobile/fenix/issues/1648, there are lots of problems with the ripples on the browser toolbar currently. 

We should make it so the ripples don't appear behind the urlTextField 

![Button presses look weird on toolbar 2019-10-07 09_46_08](https://user-images.githubusercontent.com/4400286/66331432-63257780-e8e7-11e9-9979-ef5aa47cfb47.gif)

**Comment by pocmo** [comment]
Removing the labels for now since I may address this as part of #1514

**Comment by sblatz** [comment]
This is still happening in the latest AC version. Do we have any leads on how to fix this 🤔 

@pocmo

**Comment by Amejia481** [comment]
The issue is linked to the [background that we are adding to the toolbar ]( https://github.com/mozilla-mobile/fenix/blob/2795a34b0be303b70dc713dbf11bb6aa724b29fc/app/src/main/res/layout/component_bottom_browser_toolbar.xml#L12), when non background is added we don't have the ripple on the button but after adding it we see the ripple issue. I will spend some more time late, this is what I have found so far.

**Comment by Amejia481** [comment]
For some reason, the background URL view is getting render on top the icons
 https://github.com/mozilla-mobile/android-components/blob/3aa8dc692e726f9e43ff99729656ce8156bc1084/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml#L29

If we don't call  `setUrlBackground` on Fenix the ripples work as expected
https://drive.google.com/file/d/1hXrJ_Jz4xF4EEgTWe-Jz3pgwtx0JxsUF/view?usp=sharing

Maybe it has to do we the visibility of the icon as they are initially gone and the url background view is initially visible.

**Comment by Amejia481** [comment]
If we made the url background transparent by adding `views.background.setImageAlpha(127)`  after setting the background https://github.com/mozilla-mobile/android-components/blob/3aa8dc692e726f9e43ff99729656ce8156bc1084/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt#L302 the ripple shows as expected that means the issue here is the background is getting rendered on top of the icons

**Comment by Amejia481** [comment]
Another alternative is setting the changing the directly on the drawable https://github.com/Amejia481/fenix/commit/7a497a23d2ec059a8d666830b3a5f6a66cf0aa94

The issue if that this cause the original colour to change

**Changing the transparency**
![image](https://user-images.githubusercontent.com/773158/82556078-08b7ef00-9b37-11ea-8ed3-467841337b85.png)

**without the transparency**
![image](https://user-images.githubusercontent.com/773158/82556057-ffc71d80-9b36-11ea-803c-542fa505df75.png)

**Comment by sblatz** [comment]
What's odd is when I explode this view out, the toolbar_background is behind the button as I'd expect...?  I wonder if the button's background does not render on the same z axis as the button itself? 

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4400286/82597501-eab1b500-9b5d-11ea-9641-51f8deddf807.png">

**Comment by Amejia481** [comment]
I was testing with `setTranslationZ` and `elevation` but without luck.

**Comment by Amejia481** [comment]
I'm not sure if the fact the drawable that we are setting is a solid one, it is causing issues with the ripples. We can see the icons (Tracking Protection and security indicator) are visible on top of the background but the ripple are being draw behind the background.
  
https://github.com/mozilla-mobile/fenix/blob/9ce9fbc889c8f58a3a76a9d0a40ddb74da4993f9/app/src/main/res/drawable/search_url_background.xml#L6

**Comment by mcarare** [comment]
@sblatz In https://github.com/mozilla-mobile/fenix/issues/10589 the issue was simple. The selectableItemBackgroundBorderless is drawn on the nearest parent (in hierarchy) with a non-null background. The background of the toolbar was not actually a background, but a view with background color, that obviously is "above" the parent (same parent view as for buttons), so anything drawn on the parent view (including ripples) will be drawn behind that view. If the toolbar background is set the same way here, the fix is the same. Refactor the layout, so the buttons are contained in a layout that has set the background, instead of using the view for that.

**Comment by sblatz** [comment]
@mcarare I tried wrapping all these buttons inside of a ConstraintLayout and setting the background on that, but their ripples are still being drawn behind the url bar. Please see this draft PR: https://github.com/mozilla-mobile/android-components/pull/7301

Any ideas?
