### ISSUE TITLE
Migrating device record

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4721]
Should we create a new record or re-use the existing record?

**Comment by ebalazs-sv** [comment]
I had tested this on Release, Beta, Nightly migration builds from 01/10 with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2).
For Samsung Galaxy S8 (Android 9) the device name displayed on Fennec is SM-G950F and on Fenix is samsung SM-G950F. 
For Huawei Honor 8 (Android 7.0) the device name displayed on Fennec is FRD-L09 and on Fenix is HUAWEI FRD-L09.
For Xiaomi Mi4i (Android 5.0.2) the device name displayed on Fennec is Mi 4i and on Fenix is Xiaomi Mi 4i.
@pocmo Is this the expected result? Thanks!

**Comment by pocmo** [comment]
CC @grigoryk Can you describe our expectations here?

**Comment by grigoryk** [comment]
@ebalazs-sv 

The expected behaviour is that:
- new device record is not created after a migration

You can check this by going to accounts.firefox.com, "Device & apps", before and after the migration. Before the migration, you should see your Fennec device there. After the migration, you should see the same device there, and now new devices.

Device name should also remain the same.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly migration build 01/15 with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2). The device record is the same after the migration in accounts.firefox.com, and there is no new record created. 
I will mark this as Done. Thank you!
