### ISSUE TITLE
IllegalStateException: at mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:1)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/android-components#4736]
```
java.lang.IllegalStateException: You need to call initialize() on your Push instance from Application.onCreate().
	at mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:1)
	at mozilla.components.lib.push.firebase.AbstractFirebasePushService.onMessageReceived(AbstractFirebasePushService.kt:11)
	at org.mozilla.fenix.components.FirebasePush.onMessageReceived(FirebasePush.kt:18)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
	at com.google.firebase.iid.zzc.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:762)
```

This is a recent top crash in Fenix Nightly with GV 71. We're seeing about 30+ crash reports from Fenix Nightly everyday in Socorro. Why did this unhandled Java exception get sent to Socorro instead of Sentry?

https://crash-stats.mozilla.org/signature/?product=FennecAndroid&signature=java.lang.IllegalStateException:%20at%20mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:1)&version=71.0a1&date=%3C2019-10-14T17:50:59%2B00:00&date=%3E%3D2019-10-07T17:50:59%2B00:00

Here is a crash report in Socorro:

https://crash-stats.mozilla.org/report/index/749cbf19-4c80-485a-9508-4f2230191014

This crash signature looks like A-C issue https://github.com/mozilla-mobile/android-components/issues/3827 which @jonalmeida closed as user error on his local machine. However, these crash reports are coming from Fenix Nightly users.

**Comment by pocmo** [comment]
> This is a recent top crash in Fenix Nightly with GV 71. We're seeing about 30+ crash reports from Fenix Nightly everyday in Socorro. Why did this unhandled Java exception get sent to Socorro instead of Sentry?

We started to send all crashes to Socorro (in addition to Sentry):
https://github.com/mozilla-mobile/android-components/issues/3511

Background is that we need a better way to get a feeling for the overall quality of the app. Sentry isn't suitable for that. And Google Play is something we may not be able to rely on going forward. So we would like to send everything to Socorro and see if that is good enough for assuring app quality (since it was for Fennec).

**Comment by jonalmeida** [comment]
The stacktrace says the AutopushFeature hasn't been initialized before a message from Firebase has been initialized.

However, the initialization of the feature happens in the Application class which itself is initialized first before a message is delivered, so this is a confusing crash.

What I've verified so far with a sample application with Firebase push:
 1. The application class is always instantiated first before receiving a message.
 2. The application class is always instantiated in the main process if a message is delivered when the app was swiped away (not force closed, that's different).
    - We were concerned that maybe there was some case where the app when init'd from a service was not done in the main process for some undocumented reason.
3. We can still access resource strings to get access to Firebase API keys when initi'd from the background.
4. If the app is force closed - messages will never be delivered from Firebase and no service (e.g. Play Services) restarts the app.

**Comment by jonalmeida** [comment]
A third:
 - There is some synchronization issue where the AutopushFeature is not fully initialized before the messages are delivered (again, in a way I can't explain). This seems the least likely since if it was the case it would have shown up a longer than two weeks ago.

**Comment by jonalmeida** [comment]
Since the change Leanplum push integration change came at the same time of this crash, we believe that it might be related to the crash and put up a revert for that change to see if the crashes stop (since leanplum is not currently being used).

Once that is verified, we can carefully re-integrate it following the Leanplum SDK docs and decoupling the Leanplum initialization from just the metrics service.

In addition, we also found a potential bug where we receive a Leanplum message that our AbstractFirebasePushService cannot handle.

**Comment by jonalmeida** [comment]
The crashes went back down after reverting the Leanplum integration in Fenix (mozilla-mobile/fenix#6254) so I'm happy to close this now.

Leanplum integration needs to be re-landed taking into consideration how messages need to be delivered as well as the issues mentioned above.
