### ISSUE TITLE
Improve our download manger to be able to forward downloads to external download manager

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4772]
Before performing a download we have to verify if there are other apps that download this file.

**If so:**
Create a custom intent chooser(https://github.com/mozilla-mobile/android-components/issues/4770#issuecomment-543777062) and includes the actual app on the list. If the user selects the app from the dialog immediately download the file.

**Otherwise**:
Download the file without showing an dialog chooser.

See this comment for [reference about how Fennec handles this](https://github.com/mozilla-mobile/fenix/issues/2197#issuecomment-539499506).

This feature should be configurable, the app able will be able to indicate this behavior should be applied or if the download should be download immediately.

**Comment by SS1113** [comment]
When a file is being downloaded in Fennec it starts to download the file immediately in background after clicking on the download link, doesn't matter if an external download manager is installed or not and then shows the list of apps that can handle the file including external download manager, when chosen the external download manager it passes the download file to the external download manager and then Fennec stops downloading the file in background thereby wasting precious mobile data by downloading the file in background without confirming if the user wants to download the file using Fennec or external download manager. So please fix this behaviour when implimenting this feature in Fenix/Firefox preview.

Thanks a lot for considering this feature because I mainly use a seperate download manager to download files.

**Comment by andreicristianpetcu** [comment]
Should this work with Download Navi? I can't get it to work.

**Comment by cadeyrn** [comment]
@andreicristianpetcu How did you test? Did you try in Fenix? There hasn't been an AC update in Fenix since that AC change landed.

**Comment by andreicristianpetcu** [comment]
I tried in Fenix. I'll look at ac updates next time

**Comment by andreicristianpetcu** [comment]
I tried in Fenix. I'll look at ac updates next time

**Comment by Amejia481** [comment]
> Should this work with Download Navi? I can't get it to work.

I should work with any third party app, as long as they are handling downloads intents correctly :)

**Comment by Amejia481** [comment]
The feature will be available after this pr lands
