### ISSUE TITLE
WebExtension directory can not start with underscore

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#4826]
A web extension directory under `assets` can not start with an underscore. It seems that Android by default does not include these dirs in the .apk and when installing we're failing with:

```
2019-10-22 15:50:18.966 28158-28158/org.mozilla.samples.browser E/SampleBrowser: Failed to install mozacBorderify
    java.lang.Exception: An error occurred while registering the WebExtension resource://android/assets/_extensions/borderify_test/: Error: Error while loading 'resource://android/assets/_extensions/borderify_test/manifest.json' (NS_ERROR_FILE_NOT_FOUND).
        at org.mozilla.geckoview.CallbackResult.sendError(CallbackResult.java:14)
        at org.mozilla.gecko.EventDispatcher$JavaCallbackDelegate$1.run(EventDispatcher.java:471)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4079)

**Comment by csadilek** [comment]
It seems we will have to configure `aaptOptions` / `ignoreAssetsPattern` per application: https://github.com/ionic-team/capacitor/issues/1750#issuecomment-511785165

Not sure there's anything else we can do?

**Comment by rpl** [comment]
@csadilek Another option would be likely to include the extension packed as an xpi file and then intstall the xpi file instead of the direcotry

(which would also align with what the AddonManager "officially support": on the AddonManager side we have deprecated support for unpacked extension long time ago, besides for the temporarily installed extensions because they are meant to only be used as unpacked while the extension is being developed).

**Comment by csadilek** [comment]
@rpl yes, agreed, for third-party add-ons, I don't think that's a concern, as we'd never package as part of the .apk. For first-party ones (our extensions packaged as Android components), this is something to be aware of.

**Comment by rpl** [comment]
On other platform keeping the extension packaged helps us to avoid some platform specific problems (e.g. when loading extension files from disk: MacOS is case insensitive by default, whereas Linux is case sensitive, packing the extensions resources into an xpi file ensures that loading the extension files in production is going to be case sensitive everywhere) and it also ensures the integrity of the extension (as it is signed and tempering the content of the package would make the signature checks to fail).

I think that "tempering of a first party extension" is less of a concern on android, because the first-party extension would be loaded from a part of the filesystem only accessible to the operating system and the application that contains those resources (at least if the phone's system isn't rooted).

@csadilek I think that having the extension included as a directory in the related reusable android component is definitely a simpler and natural approach for a library of reusable component, and also simpler then pre-packing the extension directory into an xpi file as part of the android components build process, but I'm wondering: would it be technically feasible? (or is there any limitation/blocker that would prefer that strategy to work).

**Comment by csadilek** [comment]
> I think that having the extension included as a directory in the related reusable android component is definitely a simpler and natural approach for a library of reusable components..

@rpl Agreed, for our current first-party extensions (ReaderView, BrowserIcons and the FxA web channel) we use an asset directory mostly because it was easier and we didn't have any problems with it. However, I am definitely up for helping and trying to add a build step that packages extension code in an .xpi. As this is essentially a .zip file (is that right?), this should be possible. We could file an issue here and give it a try. Short-term we have workaround for the underscore issue, but there may also be more benefits for an additional build step e.g. we might want to minify CSS and JS files for instance. (https://github.com/mozilla-mobile/android-components/issues/2288)

**Comment by rpl** [comment]
@csadilek :+1: sounds great to me

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796322

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
