### ISSUE TITLE
Make website icon(s) available through Engine/Session

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#494]
This is a tricky one. There are a gazillion web standards that provide icons. Different use cases may need different types of icons or sizes. Sometimes we want to do requests to get an icon, other times we only want to pull from the cache (e.g. for privacy reasons).

The code in Fennec is quite complex and tries its best to download, save, load, decode, .. icons and do things like color extraction:
https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/icons

I spend quite some time with that code and there are a bunch of pitfalls when it comes to icons.

**Comment by jonalmeida** [comment]
We're thinking that since importing this icon code, is a rather large project, we can make it simpler in a few ways:
 1. Add them into a separate component: `browser-icons`
    - This would be separate from the `ui-icons` because it doesn't include any UI elements, nor is it a feature components that contains dependent components, and it can be de-coupled from a specific engine*.
 2. Include just the basics of this module which include downloading, and storing (in-memory) the favicons.
    - There are more complicated things to do here as well that involve an disk LRU cache which have third-party dependencies that we would like to avoid using.

*The fennec implementation retrieves the icon path to be retrieved. To get this to work on system-engine as well we would need another abstraction.

## Misc
- One of the issues that turned up during the Fennec implementation, is because we're using `HttpUrlConnection` in the Java world to retrieve the icon, there are policies that the browser is aware off that we aren't, when we want to make requests.

Once we have this working, we can iterate on top this to include the more complicated caching and policies.

Favicons are going to be fun to implement. ;)

![](https://media.giphy.com/media/FMnVZzDALopvG/giphy.gif)

**Comment by pocmo** [comment]
Some random annoyances I remember from the Fennec icon code:

* Different features want different icon sizes (e.g. displaying an icon in the list of bookmarks vs. a Android home screen shortcut). I think in Fennec we try to save a rather larger icon to disk (but not too large) and load a resized version. With memory caching this gets complicated when you need different sizes at the same time.

* Favicons (and others) are defined in the DOM and this is not static. As the DOM can change so can the icon. Extreme example: https://www.favitimer.com/ 

* This bug was a bigger refacotring of the code and some of the linked issues contain some of the problems and reasons: https://bugzilla.mozilla.org/show_bug.cgi?id=1290014 - see meta bug too: https://bugzilla.mozilla.org/show_bug.cgi?id=1265712
