### ISSUE TITLE
browser-store: Consider switching to object equality for ifChanged

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#4971]
We're currently comparing identity (reference equality) when checking for changes in `ifChanged` and `ifAnyChanged`. This is somewhat unintuitive, as developers would expect their equals function to be used for the check, if provided.

This would also allow for the use of `Pair` and `Tuple` in `ifChanged`.

**Comment by pocmo** [comment]
I just noticed that internally in `Store` we use object equality too in order to determine if the state has changed at all:
https://github.com/mozilla-mobile/android-components/blob/master/components/lib/state/src/main/java/mozilla/components/lib/state/Store.kt#L104-L107

With that we probably should do that in `ifChanged` too?
