### ISSUE TITLE
Saved images can't be opened from the Android taskbar confirmation

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#5032]
**This one is related to a [Fenix bug](https://github.com/mozilla-mobile/fenix/issues/6519)**

## Steps to reproduce
1. Navigate to theverge.com
2. Long tap on one of the featured articles or images
3. Select "Save image" from the context menu
4. From the Android taskbar tap on the download confirmation to open the downloaded image 

### Expected behavior
The image should be opened after tapping the notification

### Actual behavior
The downloaded image isn't opened after tapping the notification

### Device information

* Android device: 
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

* Fenix version: 
• Beta 3.0.0-beta.1 Build #13112229 from 7/11
• Nightly Build #13120608 from 8/11

### Notes
► Video
![20191108_124622](https://user-images.githubusercontent.com/51314259/68471301-8ca72b00-0226-11ea-98c5-fb858f38913b.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4348)

**Comment by julienw** [comment]
I see a similar problem with PDF files, could you please check if this patch fixes it? Otherwise I'll file a separate issue.

STR is:
1. Go to http://www.les-enfants-perdus.com/#notre_carte
2. Click on "Voir la carte".
3. Click on "Download".
=> a PDF file should be downloaded. Then there's a small notification asking to open it. (BTW this is new, thanks, this is really a nice addition :) )
3. Click on "Open".
4. Click on the PDF reader app.
=> PDF app opens with a title `null`, then closes right away. Same behavior when I click the same item in the notification list.

Thanks!

**Comment by BranescuMihai** [comment]
Hi @julienw, yep, looked into it and it seems it's the same problem. 

[This fix will also solve our problem here](https://github.com/mozilla-mobile/android-components/issues/5046)

**Comment by sblatz** [comment]
@BranescuMihai it seems like this is still happening even after that patch 😕

**Comment by concastinator** [comment]
@BranescuMihai, what is the status of the fix for this bug? I am still encountering it in Preview 3.0.0.

**Comment by sblatz** [comment]
I wonder if this is still happening in nightly 🤔

**Comment by concastinator** [comment]
@sblatz: Indeed, it doesn't happen in Nightly anymore. I wonder, though, why Preview 3.0.0 has been released with this unpatched but well known bug. Isn't Preview supposed to be the polished version of Nightly?

**Comment by sblatz** [comment]
@concastinator we do our best to squash as many bugs as we can before each release, but we cannot get to them all. Many bugs we’re aware of have to ship or we’d never launch new stable versions. This was not deemed a release blocker for 3.0 so we moved forward with shipping it. 

That being said, since this is fixed in nightly I’m going to throw a QA needed on it to get it closed out!

**Comment by sblatz** [comment]
@sv-ohorvath are you able to verify this has been fixed? :)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792947

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
