### ISSUE TITLE
Remove the Need to Have At Least One Engine Observer to Load URI

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#5229]
Currently `GeckoEngineSession` have the assumption that there is always atleast one `EngineObserver` associated with it.  This assumption is incorrect.  Add check so if there's no `EngineObserver` then return Allow to GeckoView so it can continue to load the page.

**Comment by csadilek** [comment]
Just clarifying that the assumption here was only recently introduced for app links in https://github.com/mozilla-mobile/android-components/issues/4950.

This required the engine observer to decide whether or not GeckoView should load the URI. The current fix only addresses the case where there's no observer, but we still have a fragile situation here. What if there are multiples observers? What if there's one observer, but it doesn't override `onLoadRequest`. In case of the former we'd complete the `GeckoResult` twice and crash, in case of the latter we'd never load the URI. None of this is urgent, but since we want to get rid of `EngineObserver` anyway as we migrate to `browser-state` maybe we can think of a better solution here e.g. relying on an interceptor?
