### ISSUE TITLE
git log with --graph is unreadable in terminal: use Rebase & Merge instead

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#5450]
The git history is fairly unreadable in the terminal (and probably GUI tools) due to excessive branching:
<img width="830" alt="Screen Shot 2019-12-31 at 13 53 19" src="https://user-images.githubusercontent.com/759372/71634957-0fb88200-2bd5-11ea-9b39-3fa6cff6c33d.png">

This makes it difficult to do any type of code spelunking, regression bisection, etc.

When we merge, we should really be using GitHub's "rebase & merge" setting.

The command I run for history locally is
```sh
git log --pretty=oneline --abbrev-commit --graph --decorate --color --all
```

**Comment by jonalmeida** [comment]
This was one of the downsides with using bors unfortunately, since we can't do a rebase without having the rebase itself done on the bors servers and therefore trusting those servers. 

We used to have a nice beautiful linear git history. 😢

**Comment by mcomella** [comment]
Some potential solutions:
- Manually rebase before executing bors merge
- Let bors rebase (is this really less secure than the current setup? bors could be rewriting commits and we wouldn't know it without everyone using GPG signing. Even then, it could add commits without us noticing)
- Don't use bors
- ?

**Comment by jonalmeida** [comment]
> (is this really less secure than the current setup? bors could be rewriting commits and we wouldn't know it without everyone using GPG signing. Even then, it could add commits without us noticing)

bors merges commits to a "try" branch to test the build, and then merges that into master if it passes. Rebases would change commit SHAs IIRC.

**Comment by pocmo** [comment]
Manual rebases are not feasible. That's what we did previously and it is keeping us busy with work a tool should do.

Letting bors rebase is not possible. This is just not supported. We could contribute this feature. But so far I wasn't keen on learning [Elixir](https://elixir-lang.org/) for that. However we could consider opening an RFC for it and hoping someone else picks it up.

Not using bors is an option and I recently looked at alternatives ("[Other apps that implement the NRSROSE](https://forum.bors.tech/t/other-apps-that-implement-the-nrsrose/51)"). I tested [Mergify](https://mergify.io/) on a test repo and it looks very promising; especially since it could potentially solve some other automation issues. I was thinking about potentially testing it with the Reference Browser first.

**Comment by mcomella** [comment]
> But so far I wasn't keen on learning Elixir for that.

If only it were written in Groovy... 😞

**Comment by pocmo** [comment]
In the Reference Repository we are now testing Mergify. Primarily to auto-merge bot PRs that are green. But it also is able to do rebased merges without merge commits (what we have enabled). If successful we will likely replace bors with it here too. :)

**Comment by pocmo** [comment]
Mergify is now enabled for AC.
