### ISSUE TITLE
SessionManager never closes opened sessions, leading to OOMs

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/android-components#5933]
See [Fenix #4151](https://github.com/mozilla-mobile/fenix/issues/4151)
See attempted fix PR https://github.com/mozilla-mobile/android-components/pull/5919 (with [several problems](https://github.com/mozilla-mobile/android-components/pull/5919#pullrequestreview-358056532))

Any `EngineSession`s that are actively opened (I _**believe**_ the only way to 'open' an `EngineSession` is to select and load its tab during the current user session) will never be closed.  If too many are opened (on my device ~20) this will cause an OOM crash.  I haven't measured, but presumably there is a perf impact before that point is reached.

It's on GVs roadmap to handle this memory pressure intelligently, but it hasn't been prioritized.  For now, they recommend that we open/close `EngineSession`s ourselves.
[Riot conversation](https://matrix.to/#/!kgzqJPKsBZFakDVGxV:mozilla.org/$FRkgsypkk5TWgICW28a25EIAacze0uBUyDI_e_zdmrw?via=mozilla.org&via=matrix.org)
[BZ1](https://bugzilla.mozilla.org/show_bug.cgi?id=1587853)
[BZ2](https://bugzilla.mozilla.org/show_bug.cgi?id=1454752)

A very basic solution here could be:
- `SessionManager#onLowMemory` closes all `EngineSession`s except for the currently selected one.
- When a new tab is selected, more than MAX_SESSIONS are open, close the LRU `EngineSession`

**Comment by pocmo** [comment]
Thank you for filing this!

> - `SessionManager#onLowMemory` closes all `EngineSession`s except for the currently selected one.
> - When a new tab is selected, more than MAX_SESSIONS are open, close the LRU `EngineSession`

That sounds good. I think a combined option could work really well (react to memory pressure and make use of LRU order).

If we implement `onTrimMemory()` then we'll get a `level` and can use that to decide how aggressively we want to close sessions.

On the implementation side I think we can get a lot for free from `EngineSessionHolder`. It is the link between a `Session` and an `EngineSession`. It can also keep a `EngineSessionState` instance and will use that to lazily create an `EngineSession` with that state if needed. In fact that is what happens on session restore when the app starts: We set all the states and do not create any `EngineSession` - that will happen automatically once needed (which will then clear the state).

So in the case where we want to reduce the memory footprint of a `Session` we can save the state to `EngineSessionHolder` and then remove and close the linked `EngineSession`. It will automatically recreated if needed.

There are some edge cases we need to take care of: Not closing the selected session (since that is likely being rendered) and watching out for external sessions like custom tabs or web apps - which are never selected but may still be rendered at the moment.
