### ISSUE TITLE
Bump sentry-android to v2.0

### ISSUE THREAD

**Issue by marandaneto** [mozilla-mobile/android-components#6095]
hey, sentry-android has a brand new Android SDK with NDK support (we call it v2.0).

There's also a migration guide from v1.0 to v2.0 https://docs.sentry.io/platforms/android/migrate/

The repo now sits at https://github.com/getsentry/sentry-android

Please let us know if we can be of any help :) thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5081)

**Comment by pocmo** [comment]
Thank you. We will take a look. :)

**Comment by bruno-garcia** [comment]
There were quite [a few new releases](https://github.com/getsentry/sentry-android/releases) since this issue was raised.

One of the new features is support to Sentry's [release health](https://blog.sentry.io/2020/05/19/crash-free-sessions-carefree-users-with-release-health).

Let us know if there's something we can do to help.
