### ISSUE TITLE
Introduce a Cache for TopSites to improvement Fenix Cold Start performance

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/android-components#6174]
## Description of Problem

Fenix measures its cold start performance (at the moment) when `onBindViewHolder` occurs for its RecyclerView TopSites. On a G5+ we saw a cold start up time of ~870ms.  I noticed that we had multiple layout passes triggered and a wait time from our `homeFragmentStore.dispatch` which lead to a noticeable delay

## Proposed Solution

Introduce a cache in the form of SharedPreferences where we can load the Users' TopSites through there on start.  I.e:

```
 fun getTopSitesFromPrefs() : List<TopSite>
    {
        val topsites = mutableListOf<TopSite>()
        pref.all.forEach {
            topsites.add(
                TopSitePrefs(
                    Entity(
                        it.key, it.value.toString(), UUID.randomUUID().leastSignificantBits
                    )
                )
            )
        }
        return topsites
    }
```

where `Entity()` is the same as our `TopSiteEntity` at the moment.

This solution seems to bring down start up time on the G5+ to 700ms.
Here are two apks built with TopSites from Room and TopSites from SharedPref: https://drive.google.com/open?id=1eMtvsLVw52zH7XA7YzUE1sIcxmtRUYWm

**Comment by gabrielluong** [comment]
I will probably take on this investigation.

**Comment by csadilek** [comment]
Just created a custom release build which measures and logs topsite storage initialization time, as well as the time spent actually querying top sites. Even if I add lots of custom topsites, both times are < 1ms on my Pixel 3.

I think the variance seen here originally must have been caused by something else e.g. debug builds or simply startup variance we know we have or a problem that was fixed in the meantime.

@MarcLeclair let's chat about this and compare notes. Something, doesn't line up anymore.

**Comment by csadilek** [comment]
Just created a custom release build which measures and logs topsite storage initialization time, as well as the time spent actually querying top sites. Even if I add lots of custom topsites, both times are < 1ms on my Pixel 3.

I think the variance seen here originally must have been caused by something else e.g. debug builds or simply startup variance we know we have or a problem that was fixed in the meantime.

@MarcLeclair let's chat about this and compare notes. Something, doesn't line up anymore.

**Comment by MarcLeclair** [comment]
Talked with @csadilek and he measured the time for initializing RoomDB and the time it takes to retrieve our TopSites and it seems like that isn't an issue. The work around I mentionned initially seems to be solving symptoms from another problem. Closing this for now.
