### ISSUE TITLE
Auto-publication: improve up-to-date checks

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#6233]
Currently in order to check if a-c needs to be re-published, a compilation is done. Specifically, Fenix will run `compileReleaseKotlin`, and look at gradle output. The logic is:
```
def compileTasksExecuted = compileOutput.toString().split('\n').last().split(':')[1].split(' ')[1]
if (compileTasksExecuted.equals("1")) {
    log("android-components are up-to-date, skipping publication.")
} else {
    log("android-components changed, publishing locally...")
}
```

This is problematic for two reasons:
- if a-c was compiled "out of band" of the autoPublish flow - e.g. manually, to run tests, and then a Fenix auto-publication build runs - it will execute a compile task, determine that nothing changed, and skipped re-publication. Thus, the out-of-band changes won't make it into the build.
- when nothing changed in a-c, we're incurring a compilation overhead - builds are incremental, so this is rather small; on my machine (top spec 16" macbook) it's 5-6 seconds of overhead, and could be much worse on slower machines

One alternative I'd like to explore is to rely on git hashes in order to see if any files changed. Not all tracked files changing will equate to "we need to re-publish a-c", but let's consider that an optimization, and deal with it in a follow-up.

**Comment by grigoryk** [comment]
Currently the "is a-c up-to-date?" logic lives in Fenix.

As Part 1, let's move it into A-C, which will allow us to 1) manage it here, and 2) easily re-use it in other A-C consumers, such as FxR and Lockwise.

**Comment by rfk** [comment]
> Currently the "is a-c up-to-date?" logic lives in Fenix.

FWWIW, in https://github.com/mozilla/application-services/pull/2690 I've been experimenting with a dedicate `./gradlew autoPublishForLocalDevelopment` command for this, so that we can try different strategies for skipping or running the build, and the upstream consumer projects don't need to know anything about the details.

Currently it just publishes a new build every time, regardless of whether anything changed, but it's a start :-)
