### ISSUE TITLE
PushError$MalformedMessage: parsing encrypted message failed: java.util.NoSuchElementException: Key body is missing in the map.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6415]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7662509/

```
PushError$MalformedMessage: parsing encrypted message failed: java.util.NoSuchElementException: Key body is missing in the map.
    at mozilla.components.lib.push.firebase.AbstractFirebasePushService.onMessageReceived(AbstractFirebasePushService.kt:14)
    at org.mozilla.fenix.components.FirebasePushService.onMessageReceived(FirebasePushService.kt:1)
    at com.google.firebase.messaging.FirebaseMessagingService.zzd
    at com.google.firebase.iid.zzc.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
...
(3 additional frame(s) were not displayed)

[INFO] parsing encrypted message failed: java.util.NoSuchElementException: Key body is missing in the map.
```

**Comment by pocmo** [comment]
@jonalmeida Saw that happen in a Beta migration build. Since it is "info" level I am not sure if we need to act on it?

**Comment by pocmo** [comment]
Sentry issue: [FENIX-FENNEC-BETA-2A](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7662037/)

**Comment by jonalmeida** [comment]
Yes, this is the same as I mentioned here: https://github.com/mozilla-mobile/android-components/issues/6418#issuecomment-605048112

**Comment by grigoryk** [comment]
@jonalmeida seeing a lot of this in regular Fenix builds (https://sentry.prod.mozaws.net/operations/fenix/issues/7577599/) - are you sure this is normal? Seems like a mismatch of expectations to me.

**Comment by jonalmeida** [comment]
The errors say we received a valid AutoPush message (because it containers the 'chid' value) but we don't have a 'body'. We drop the messages at the push service level since we're not able to decrypt a message without a body.

I can verify this with @jrconlin but I believe there's not much we can do with a message that does not have these [three values](https://searchfox.org/mozilla-mobile/source/android-components/components/lib/push-firebase/src/main/java/mozilla/components/lib/push/firebase/AbstractFirebasePushService.kt#55-57), the other two are optional.

If it was an optional value, following the code through to the native layer, we would hit [this call](https://searchfox.org/mozilla-mobile/source/application-services/components/push/src/crypto.rs#180-182) which would lead to a TranscodingError when we try to base64 decode it first.

I'll double-check this on Monday.

**Comment by jonalmeida** [comment]
> I can verify this with @jrconlin but I believe there's not much we can do with a message that does not have **these three values**, the other two are optional.

Looking at the AutoPush FCM router, I think my memory is accurate. We need to always have `chid`, `body`, and `con` values to continue with decryption: https://github.com/mozilla-services/autopush/blob/master/autopush/router/fcm.py#L174-L182

**Comment by grigoryk** [comment]
Why are we getting push messages, from auto-push, without `body`?

**Comment by jrconlin** [comment]
So it turns out that there is the potential for an empty "tickle" push message. There are a few use cases for these (including encryption testing, since they can be delivered without any ECE encryption, and thus removing one thorny variable from the mix). The function of these "tickle" messages with the app is basically an empty "poke" event.  

This message should have no encryption header info, nor any body. I believe this could be resolved by having either the Kotlin or the lower rust code check to see if there is no header data and no body and return an empty binary array.

**Comment by st3fan** [comment]
At the least we should not report an info message and just ignore it otherwise this will go crazy on production.

**Comment by jonalmeida** [comment]
This should be fixed now. I'm monitoring sentry to see if the crashes go down when we have a new build for fenix.

**Comment by jonalmeida** [comment]
Looking at our crashes, the MalformedMessage no longer shows up in large amounts on Fenix nightly. Closing this as fixed with the changes that landed.

We have also removed the nightly-only flag from WebPush integration: https://github.com/mozilla-mobile/fenix/issues/9338
