### ISSUE TITLE
Engine: cleanup/clear data

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#644]
Parent: #200

We need to offer a way to clear the browsing data. For now that doesn't need to be a fine-grained API. Just remove everything.

* In Focus (WebView build) that's used for removing all data after the end of a browsing session
* In the Fire TV app there's a setting to clear the browsing data

For Focus and private browsing that may be handled in #499 already.

For our existing apps we'd only need to support this in WebView for now.

**Comment by psymoon** [comment]
In the Fire TV app, clear methods depend on WebView instances which could potentially cause problems if we refactor. Right now, we initiate another "invisible" WebView instance in our SettingsFragment to clear user browsing data - please see https://github.com/mozilla-mobile/firefox-tv/issues/1005

**Comment by pocmo** [comment]
Implementation in Firefox for Fire TV:
https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/amazonWebview/java/org/mozilla/focus/ext/AmazonWebView.kt#L12-L30

Implementation in Focus for Android:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/webview/SystemWebView.java#L241-L260

**Comment by jonalmeida** [comment]
Since code is continuous moving in the other repositories, here are the snippets of code that was linked above:

```java
@Override
public void cleanup() {
  clearFormData();
  clearHistory();
  clearMatches();
  clearSslPreferences();
  clearCache(true);

    // We don't care about the callback - we just want to make sure cookies are gone
  CookieManager.getInstance().removeAllCookies(null);

  WebStorage.getInstance().deleteAllData();

  final WebViewDatabase webViewDatabase = WebViewDatabase.getInstance(getContext());
    // It isn't entirely clear how this differs from WebView.clearFormData()
  webViewDatabase.clearFormData();
  webViewDatabase.clearHttpAuthUsernamePassword();

  deleteContentFromKnownLocations(getContext());
}
```

The part that @psymoon is referring to is:

```kotlin
fun deleteContentFromKnownLocations(context: Context) {
  ThreadUtils.INSTANCE.postToBackgroundThread(Runnable {
    // We call all methods on WebView to delete data. But some traces still remain
    // on disk. This will wipe the whole webview directory.
    FileUtils.deleteWebViewDirectory(context)

    // WebView stores some files in the cache directory. We do not use it ourselves
    // so let's truncate it.
    FileUtils.truncateCacheDirectory(context)
  })
}
```

The concern was that we needed to have an instance of WebView to clear the data (`deleteContentFromKnownLocations`) when in a different context (e.g. SettingsFragment).

While `deleteContentFromKnownLocations` clears the filesystem, we know now that this is something that we actually _shouldn't_ be doing which takes away the need to invoke that function.

So for SystemWebView, we should just make the same calls to clear all data as  in the first code snippet.

For GeckoView, we can see that [Fennec][1] does this by the event dispatcher using a list of all the attributes that we would data to be deleted from. This isn't the recommended way that we would like to be doing things, so [bug 1489669][2] was filed to get a better API from them.

Until then, we simply won't implement a GeckoEngineSession version for this.

[1]: https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/preferences/PrivateDataPreference.java
[2]: https://bugzilla.mozilla.org/show_bug.cgi?id=1489669
