### ISSUE TITLE
Generate API DIfferences Report for releases

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#667]
Android generates these API Differences Reports:
https://developer.android.com/sdk/api_diff/27/changes

And they are quite helpful if you have been working with the API before and just want to see what changed.

The GeckoView wants something similar:
https://bugzilla.mozilla.org/show_bug.cgi?id=1458668

**Comment by pocmo** [comment]
You can write a custom renderer for dokka. If we'd write one that could output the API as JSON or something else that is easier to read and diff from code then we could write something that outputs a nice diff format by comparing two JSONs (previous version and current version).

Related: https://medium.com/@flbenz/how-does-kotlins-documentation-engine-dokka-work-and-can-it-be-extended-5e83dc663ef7

**Comment by ncalexan** [comment]
I'm not sure that it's (re-)usable, but modern build systems like Buck and Bazel -- and maybe even modern Gradle -- capture the exposed API of Java (maybe even all JVM?) libraries in order to determine if downstream consumers need to be recompiled.  It might be worth investigating if somebody has already solved this problem and we can "just use" their work.

**Comment by pocmo** [comment]
Just came across this tool in the Kotlin repository:
https://github.com/JetBrains/kotlin/tree/master/libraries/tools/binary-compatibility-validator

**Comment by colintheshots** [comment]
Nice find!

**Comment by pocmo** [comment]
Looking through old issues and closing them if they are not applicable anymore.

There's not really a need for API reports at the moment... so let's just close this for now.
