### ISSUE TITLE
FXP-966 ⁃ Avoid inflation of both display and edit toolbar on creation of BrowserToolbar

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/android-components#6944]
When creating the BrowserToolbar, we usually (at least in Fenix) trigger the `editMode` right away. This means that we don't use the display layout instantly. 

We should avoid inflating both layout by either 1) combining both in one ( not sure how feasible that is) or 2) Try using `AsyncLayoutInflater` for the layout that isn't being used right away since we're able to add the view to the root contained. 

For  quick test, I allowed Fenix to just inflate the `Edit` toolbar, and saw a good ~20-30ms decrease in time from going from the `HomeFragment` to the `SearchFragment`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXP-966)

**Comment by pocmo** [comment]
Here's my analysis...

### Measurements

I started by measuring the time it takes to inflate and add the views (on a Pixel 3, values in ms).

|  Run | Inflate Display Layout  | Inflate Edit Layout  | Adding Views  |
|---|---|---|---|
| 1  | 44.639692 | 24.763752  | 0.175990  |
| 2  | 43.029588 | 25.660732  | 0.173333  |
| 3  | 43.390525 | 23.173023  | 0.174271  |
| 4  | 43.232661 | 23.029325  | 0.176875  |
| 5  | 43.359015 | 23.663440  | 0.174375  |

So, yeah, just looking at those raw numbers I agree that there may be an opportunity to save 20ms or 40ms of inflation time if only one layout is needed. Note that those numbers are from a **debug** build. I want to repeat those on a **release** build since those tend to have a better performance when inflating layouts.

### Combining layouts

I first tried the option of combining the layouts since that was fairly easy to do. With that I got the following measurements (again Pixel 3, debug build, values in ms). Since with a combined layout we need to lookup the individual views, so that we can reference them, I added the lookup time too. I didn't need to measure the time it took adding the views because for a combined layout the inflater will do that for us and that time is already included in the inflation time.

|  Run | Inflate Combined Layout  | Lookup Display Layout (ns)  | Lookup Edit Layout (ns) |
|---|---|---|---|
| 1 | 72.012299 | 8958 | 15938
| 2 | 71.849747 | 7761 | 15156
| 3 | 69.390268 | 9739 | 16250
| 4 | 69.519851 | 9062 | 18490
| 5 | 70.908393 | 8593 | 20833

So here the combined inflation time is pretty much the same as the sum of the standalone inflation time and we do not win anything. In addition to that the combined file is horribly large and pretty much unmaintainable in the visual editor.

### Asynchronous inflation

I didn't test this because with the current toolbar architecture this is a pretty large project to change. Since calls on the toolbar may get forwarded to the edit and display toolbar the lazy inflation would have no effect since they'd pretty much both get inflated immediately anyways.

### Separating toolbars

The architecture of the toolbar is borrowed from Fennec where we have a display and an editing portion. The toolbar then can switch between both modes. We used the same model and integrated it that way into the sample browser and reference browser. Unfortunately that model has downsides with the way Fenix uses the toolbar, where two separate fragments are responsible for displaying and editing the URL. That means that in Fenix always only one part is needed (editing or displaying).

If we take the idea of lazy inflation and apply it to the toolbar as a whole then we could think about separating both toolbar modes into standalone usable views. We still have a toolbar that can switch between modes, but you could also just use the edit toolbar part or the display toolbar part in your app, if you like. I think that is an approach I would prefer over only making the layouts inflated lazily which because of the delegate model doesn't work as lazily as one would hope.

Separating the toolbars is a project we could plan and think about. However it is a big change. And it is a change I would prefer to not make at this time where we need to focus on stability primarily.

### Summary

It looks like we cannot gain a "quick win" by only changing the way we inflate layouts. However there's an opportunity to potentially refactor the toolbar architecture. But that is a bigger project. As a next step I would like to repeat the measurements on a release build to get some "real world" numbers. Only if those numbers look like the debug build numbers then it may make sense to pick that up eventually.

**Comment by MarcLeclair** [comment]
So that is what I noticed too. The Async Inflation only worked on the fenix side by the way, so maybe I didn't write my explanation well enough.  What I was thinking is, would it be possible to do something similar of "Lazy inflation" ? I.e: We create the toolbar with an attribute `isEditable` which would allow us to not inflate the display portion right away. However, we could inflate the display only when we're going to need it since we add it to the root view. So  the total performance time is still the same, but our perceived performance from going from the home screen to the search screen is still faster. Would that be possible?

**Comment by mcomella** [comment]
For high-level context, I want to try to meet our release criteria for clicking the URL bar and entering the search screen (which is 300ms). MarcLeclair mentioned it was around 450ms right now. If we can't find an approach here, we should try to identify alternatives to improve it (though it sounds like we may need to make other improvements too given how large it is).

**Comment by pocmo** [comment]
> What I was thinking is, would it be possible to do something similar of "Lazy inflation" ? I.e: We create the toolbar with an attribute isEditable which would allow us to not inflate the display portion right away.

That's what I looked at too above. The problem with that is that some of the `BrowserToolbar` public API will delegate calls to **both** the display and edit toolbar - which will then cause both layouts to get inflated anyways. And this is not easy to change without a bigger change in how the toolbar works and what APIs it exposes. At this point I think we should prefer to separate the toolbars, so that they can be used without the `BrowserToolbar` wrapper if that is desired in an app.

> For high-level context, I want to try to meet our release criteria for clicking the URL bar and entering the search screen (which is 300ms). MarcLeclair mentioned it was around 450ms right now. If we can't find an approach here, we should try to identify alternatives to improve it (though it sounds like we may need to make other improvements too given how large it is).

Happy to help with that. Do we already have a breakdown of areas that are taking the most time in that workflow (besides the toolbar inflation here)?

**Comment by mcomella** [comment]
pocmo & csadilek mentioned this isn't a good time to make this change and I agree: let's take this out of the top 10.

**Comment by mcomella** [comment]
triage: we want to wait for non-startup responsiveness tests before investing in improvements.

**Comment by MarcLeclair** [comment]
Closing since this would be a huge refactor. We can always reopen this issue if we see that the inflation could be a performance gain.
