### ISSUE TITLE
Make TabsTray extensible with custom views

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#7079]
Currently the TabsAdapter only displays tabs based on the browser state. If you want to implement some more complex UI (see attached image for example) we will need some hooks to be able to add our own views to the RecyclerView. One idea is to maybe use the new [`MergeAdapter`](https://developer.android.com/reference/androidx/recyclerview/widget/MergeAdapter) when RecyclerView v1.2.0 ships

<img width="422" alt="image" src="https://user-images.githubusercontent.com/1250545/82696555-109d8f00-9c1c-11ea-87af-d13172323b3e.png">

**Comment by jonalmeida** [comment]
Thanks for filing! `MergeAdapter` looks pretty cool, we should definitely check it out.

**Comment by jonalmeida** [comment]
We have a better idea what work is involved in getting this to work in order to support content from different adapters on the tabs tray.
 - Deprecate the BrowserTabsTray: we use this class only for passing the styling from the XML to the TabsAdapter. This assumes a one-to-one relationship between an adapter and a RecyclerView which makes it impossible to use fancy new APIs like the `ConcatAdapter` (previously known as `MergeAdapter`).
 - Pass the `TabsTrayStyling` directly to the `TabsAdapter`.
