### ISSUE TITLE
Add downloads management support to DownloadManager

### ISSUE THREAD

**Issue by keianhzo** [mozilla-mobile/android-components#7227]
In FxR we are currently using a custom `DownloadManager` based implementation for Downloads. We would like to migrate to `FetchDownloadManager` to unify the Http stack using a `GeckoWebExecutor`.

One of the issues we have found is that `FetchDownloadManager` doesn't support Downloads querying/removing and we need that to update the UI: get downloads status, remove a download/s, etc

It would help if `FetchDownloadManager` provided a querying mechanism similar to the `DownloadManager` query and remove methods so we can get the current downloads status or cancel/stop/remove downloads. 

As an alternative the completed downloads could be fed to the `DownloadManager` so we could always get the finished downloads and get the ongoing through `onDownloadStopped` but we would still be missing some downloads management methods like cancel/stop/remove.

**Comment by pocmo** [comment]
For the in-memory state (e.g. showing status) #7050 will be helpful since that will move all the internal state from the service to our browser store where components the app (and UI) can use it. (which may be another reason to use the FxR <-> AC bridge). With that I think we may also be able to provide "use cases" that allow to cancel, stop etc. currently active downloads. Adding a persistent storage to that is something we eventually want to do too, but that is a bigger project.
