### ISSUE TITLE
Uplift search telemetry extensions from Fenix

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#7249]
Fenix added two built-in web extensions we should consider bringing to A-C. The extensions actually already use mozac in their name :).

**Comment by mcomella** [comment]
The changes for this issue caused a large regression on start up: https://github.com/mozilla-mobile/fenix/issues/20934 It appears the root cause is that many permissions were added to the manifest, causing the parsing to take an extended period of time: see https://github.com/mozilla-mobile/fenix/issues/20934#issuecomment-904213270 for an analysis.

@Mugurell btw, can this be closed?

**Comment by Mugurell** [comment]
Left a comment on fenix # 20934 about an alternative approach.

This ticket can probably be closed since the functionality was verified on both Fenix and Focus.
