### ISSUE TITLE
Resizing BrowserToolbar buttons

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/android-components#741]
We are setting up our toolbar by adding `Actions` to a `BrowserToolbar`, but have a requirement to change the size of the toolbar buttons.  Is there any way to do this using the existing API?  It seems that the `ImageButton`s are using each image's intrinsic size, so modifying a vector asset's size is an effective workaround, but we would rather not maintain multiple sets of icons at different sizes.

How would you suggest we approach this?

**Comment by mcomella** [comment]
We also need to divorce the asset size from the touch target size.

**Comment by mcomella** [comment]
It appears the buttons touch target's size themselves according to the toolbar content size (i.e. the height minus the padding) and the icons take their intrinsic size. Since our icons are the size we want and the touch target size we want is the size of the toolbar content, we've actually solved this problem.

**Comment by mauryat** [comment]
@NotWoods is this still valid? Can you assign it to me?

**Comment by NotWoods** [comment]
As far as I know this is still valid.

**Comment by pocmo** [comment]
Looking through old issues and closing them if they are not applicable anymore.

Currently this is not needed and in the long-term we may look at moving components like this to Jetpack Compose.
