### ISSUE TITLE
[Bugs] Reader mode url issues.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#7455]
There are a couple of problems in Fenix that are related to the reader mode extension url:

- Incorrect shared url : https://github.com/mozilla-mobile/fenix/issues/11798
- Cannot pin shortcut with reader mode https://github.com/mozilla-mobile/fenix/issues/11699.

This are caused by the session url being `moz-extension://eb8df45a-895b-4f3a-896a-c0c71ae5f6ed/readerview.html?url=...`

A quick fix would be parsing session url with `isExtensionUrl` `true` and extract the `initialUrl` (or a method to fetch the initial url).

@pocmo, @csadilek Is there another better approach to this?

**Comment by pocmo** [comment]
Looking at Fennec it seems like that's what we did too:
* https://searchfox.org/mozilla-esr68/search?q=ReaderModeUtils.stripAboutReaderUrl&path=
* https://searchfox.org/mozilla-esr68/source/mobile/android/base/java/org/mozilla/gecko/reader/ReaderModeUtils.java#48-61

Mapping the URL everywhere seems tedious, error-prone and like something we will forget for every new code we write. I wonder if we need a more generic way of distinguishing between the actual URL and a "user-facing" version of the URL? We also have this issue about sharing the canonical URL - maybe there's some way we can handle all those cases centrally in AC?

How do we currently handle the URL for the toolbar in that case? Since that seems to display the original URL already?

Will think about this a bit more.. :)

**Comment by pocmo** [comment]
Looks like the store already rewrites the reader URL here:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewMiddleware.kt#L65-L91

I assume the things in Fenix that display the extension URL are not using the store yet and use a `Session` from `SessionManager`? In that case this would be a good opportunity to migrate those pieces over. See also Fenix issues in the "migration backlog" column here: https://github.com/orgs/mozilla-mobile/projects/31

**Comment by csadilek** [comment]
@pocmo @mcarare Yes, this is a known limitation, and we filed it a while ago: https://github.com/mozilla-mobile/android-components/issues/2879.

Now that we finally have reader view implemented as an extension page it would be good to move this issue forward as well. There's a long discussion in the linked BZ, however, that ended without a resolution.

`moz-extension://` URLs are only stable per device, some we need `about:reader` support or a similar type of URL mapping for extensions: https://bugzilla.mozilla.org/show_bug.cgi?id=1322304

Another option would be GV API to create a history entry mapping? Let's continue in https://github.com/mozilla-mobile/android-components/issues/2879

**Comment by csadilek** [comment]
See also: https://github.com/mozilla-mobile/fenix/issues/5190

**Comment by ebalazs-sv** [comment]
This will be continued in #2879, due to that I will move this issue to Done.
