### ISSUE TITLE
Create recycler view helper to handle empty & loading states

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#7950]
These two states are very common for lists in Fenix and other apps. We should encapsulate this logic into a helper class that can handle showing different views when lists are empty and when data is still loading.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6892)

**Comment by jonalmeida** [comment]
This is interesting! I wonder if you've noticed a pattern in other RVs. 

In some of the work I've done, we've used the feature to notify the view when there are empty and loading states, so that we can show a different UI/layout until that is complete. For example, in [`SyncedTabsView`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/view/SyncedTabsView.kt) we have start and stop loading notifications for the view to handle it.

Maybe an interface that features can add to their views like a `LoadingFeature` (this is a terrible name, please don't use it!):

```kotlin
interface LoadingFeature {
  fun startLoading()
  fun stopLoading()
}
```

We could then implement this on a RecyclerView helper like you suggested that we can get for free if that is used, or the app can implement that differently if they want to do something else custom. The empty state is something that probably can go straight into the helper I'd imagine?

**Comment by NotWoods** [comment]
I haven't seen too many instances where a recycler view is tied directly to an AC feature in Fenix. Since loading can be easily represented as a boolean state (or enum if you want to separate success/failure), I think it makes more sense to just expose a setter and re-evaluate later if we see patterns emerge.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795384

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
