### ISSUE TITLE
LoginsStorage.wipeLocal doesn't work as expected

### ISSUE THREAD

**Issue by keianhzo** [mozilla-mobile/android-components#8079]
For what I read in the docs `LoginsStorage.wipeLocal` should: 

> Clear out all local state, bringing us back to the state before the first sync.

So if you add logins to the storage, then sync and the call `LoginsStorage.wipeLocal`, you should still see the original logins before syncing but it doesn't seem to be the case.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6992)

**Comment by linacambridge** [comment]
Oooh, good catch! I _think_ this is a documentation error inside a-s, coupled with assumptions about our consumers.

`wipe`, `wipeLocal`, and `reset` do overlapping but very different things:

* `wipe` deletes all logins (but _not_ Sync metadata—the sync ID and last sync time will remain) from the database _and_ uploads tombstones for them, so those logins will also be deleted on all other devices.
* `wipeLocal` deletes all logins _and_ Sync metadata from the database, but does _not_ upload any tombstones, so they'll remain on other devices.
* `reset` deletes _only_ Sync metadata from the database, leaving all logins. (It also doesn't upload any tombstones).

It sounds like the thing you want is `reset`—but its docs say [deprecated in favor of `wipe` and `wipeLocal`](https://github.com/mozilla/application-services/blob/f8fb86ad8b0ae4d443af97cf4d2a230be8cb32c2/components/logins/android/src/main/java/mozilla/appservices/logins/LoginsStorage.kt#L94), which are not the same.

I think the docs and the component were written with the assumption that Lockwise is our consumer. In Lockwise, signing out _should_ call `wipeLocal`—since it's not possible to use Lockwise without an account, and we don't want to leave the user's old synced passwords in the database. But it's not the right thing to use for FxR (and Fenix, and Desktop), where signing out should leave the passwords unless the user [specifically asks to delete them](https://bugzilla.mozilla.org/show_bug.cgi?id=1657463).

On the a-s side, I think we'll want to:

1. Undeprecate `reset`, and rename it to something more verbose, like `resetSyncMetadata`. Expose this in a-c, too.
2. Improve the docs for `wipe` and `wipeLocal` to clarify what they delete and from where. "All local state" reads kind of ambiguously now.
3. Clarify which methods are meant for which consumers. Lockwise should call `wipeLocal` after signing out; everyone else should call `resetSyncMetadata`.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795383

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
