### ISSUE TITLE
check_all_dependencies_are_completed fails build when tasks are not completed

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8138]
Failing PR: https://github.com/mozilla-mobile/android-components/pull/8134
Task link: https://firefox-ci-tc.services.mozilla.com/tasks/EexFUcyPTjuaAvCchiuwcQ

```
[vcs 2020-08-17T22:56:55.261Z] HEAD is now at 6d06ea516 Merge #8134
[vcs 2020-08-17T22:56:55.262Z] executing ['git', 'clean', '-xdff']
[vcs 2020-08-17T22:56:55.327Z] TinderboxPrint:<a href='https://github.com/mozilla-mobile/android-components/commit/6d06ea516d3a48785fcc9756d339e191b006e9a5' title='Built from android-components commit 6d06ea516d3a48785fcc9756d339e191b006e9a5'>6d06ea516d3a48785fcc9756d339e191b006e9a5</a>
[task 2020-08-17T22:56:55.327Z] executing ['bash', '-cx', '/builds/worker/checkouts/src/taskcluster/scripts/are_dependencies_completed.py cItg8lYjTRWdYLqe_ZECRA JeCyFC7LQjmvAoKIYHQzWw']
[task 2020-08-17T22:56:55.329Z] + /builds/worker/checkouts/src/taskcluster/scripts/are_dependencies_completed.py cItg8lYjTRWdYLqe_ZECRA JeCyFC7LQjmvAoKIYHQzWw
[task 2020-08-17T22:56:55.573Z] Fetching status of 2 dependencies...
[task 2020-08-17T22:56:55.573Z] Statuses fetched.
[task 2020-08-17T22:56:55.573Z] Traceback (most recent call last):
[task 2020-08-17T22:56:55.573Z]   File "/builds/worker/checkouts/src/taskcluster/scripts/are_dependencies_completed.py", line 52, in <module>
[task 2020-08-17T22:56:55.573Z]     main()
[task 2020-08-17T22:56:55.573Z]   File "/builds/worker/checkouts/src/taskcluster/scripts/are_dependencies_completed.py", line 46, in main
[task 2020-08-17T22:56:55.573Z]     check_all_dependencies_are_completed(result.dependencies_task_ids)
[task 2020-08-17T22:56:55.573Z]   File "/builds/worker/checkouts/src/taskcluster/scripts/are_dependencies_completed.py", line 32, in check_all_dependencies_are_completed
[task 2020-08-17T22:56:55.573Z]     raise ValueError('Some tasks are not completed: {}'.format(non_completed_tasks))
[task 2020-08-17T22:56:55.573Z] ValueError: Some tasks are not completed: {'JeCyFC7LQjmvAoKIYHQzWw': u'failed'}
```

cc @mozbhearsum who I think worked on this.

**Comment by mozbhearsum** [comment]
I will dig into this today or tomorrow, feel free to assign to me (I don't have permissions to do that myself).

**Comment by mozbhearsum** [comment]
I might be missing something, but this looks like a legitimate failure to me.
* The link above cites https://firefox-ci-tc.services.mozilla.com/tasks/JeCyFC7LQjmvAoKIYHQzWw as failing, which is `complete-push-1`
* The above task cites https://firefox-ci-tc.services.mozilla.com/tasks/csdLKqsPR9yxhNCnncubyA as failing, which is `build-feature-search`
* That task is failing with `Execution failed for task ':feature-search:testReleaseUnitTest'.`

`complete-push-2` is also failing because `test-ui-browser` is failing (https://firefox-ci-tc.services.mozilla.com/tasks/DcEpkhOpRAW-oy8CMTBMuA).

Please let me know if I'm missing or have misunderstood something here.

**Comment by jonalmeida** [comment]
@mozbhearsum oh my mistake! I must have misread the failed tasks.

In that case, this sounds like a duplicate of https://github.com/mozilla-mobile/android-components/issues/8124
