### ISSUE TITLE
Autofill arrow always pastes the suggestion title

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/android-components#8175]
It should autofill the url for bookmarks or history entries, and be hidden for search engines or the first search suggestion (that is always exactly what the user has typed). See fenix issues https://github.com/mozilla-mobile/fenix/issues/13835, https://github.com/mozilla-mobile/fenix/issues/13768 and https://github.com/mozilla-mobile/fenix/issues/13520.
I will open a PR here to try to fix this. :)

**Comment by crisalis2** [comment]
@miDeb @pocmo May I suggest something?

For search engines, maybe the arrow could still show and have the function to just change to that search engine (without actually submitting the search).

Right now, this "change to search engine without actually searching" is what happens when you tap on a search engine, and then to actually search you have to press enter in the keyboard, which seems like unnecessary effort.

So tapping on a search engine could directly search, and tapping on the arrow could just change to the engine. This way, the behaviour with search engines would be similar to what happens with bookmarks, etc. And searching with another search engine would be easier.

**Comment by miDeb** [comment]
@crisalis2 the relevant issue for that is https://github.com/mozilla-mobile/fenix/issues/4333.
