### ISSUE TITLE
GeckoView Nighly/Beta update failing

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8209]
https://firefox-ci-tc.services.mozilla.com/tasks/GpGq8GTFS7i4fnH5iFpfIQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FGpGq8GTFS7i4fnH5iFpfIQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

There seems to be an API breakage in the latest Nightly:

```
e: /build/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt: (57, 58): Return type of 'onTouchEventForResult' is not a subtype of the return type of the overridden member '@NonNull public open fun onTouchEventForResult(@NonNull p0: MotionEvent): GeckoResult<Int!> defined in org.mozilla.geckoview.GeckoView'
e: /build/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt: (106, 16): Type mismatch: inferred type is GeckoResult<Int!> but Int was expected
```

**Comment by pocmo** [comment]
From the error it looks like `onTouchEventForResult` changed.

@Mugurell Do you know about this change? :)

**Comment by Mugurell** [comment]
Seems to be https://bugzilla.mozilla.org/show_bug.cgi?id=1633322 - https://phabricator.services.mozilla.com/D86384.
Not sure about why the change to a GeckoResult and I'm also a bit concerned about :

> NOTE: It is highly recommended to only call this with ACTION_DOWN or in otherwise
limited capacity. Returning a GeckoResult for every touch event will generate
a lot of allocations and unnecessary GC pressure.

since we are actually piping [all events through that](https://github.com/mozilla-mobile/android-components/blob/cd134a34c94a4419167aa55b7c09babc9b6f60d8/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt#L57)

@snorp ?

**Comment by pocmo** [comment]
Looks like this change also made it in right before 81 Beta was cut. So we now have the same issue updating to 81 Beta.

**Comment by Mugurell** [comment]
I'm looking into this but I'm seeing that now swipes in google maps are returning `INPUT_RESULT_HANDLED` 
based on which we would erroneously animate the toolbar.

**Comment by liuche** [comment]
Looks like the GV change got backed out of 81, but will still be in 82: https://bugzilla.mozilla.org/show_bug.cgi?id=1633322#c42

1) I'm assuming that this will work on 81 Beta now, without any additional changes, so we can pick up the GV81 Beta? (We are planning on cutting Fenix 81 Beta 12PST 8/26, which will need an AC dot release with GV81 Beta as well)
2) Fix still required for 82 Nightly
