### ISSUE TITLE
Task graph does not rebuild components that are dependant on other components that have changed

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8265]
For this PR, I've touched `browser-session` and `browser-state`, so I would have expected all components that have those two as a dependency to be rebuilt: https://github.com/mozilla-mobile/android-components/pull/8250

Instead, I only see a handful of tasks created after the graph has been pruned: https://firefoxci.taskcluster-artifacts.net/HB9ZUbeESpGtZX1b-F61xw/0/public/target-tasks.json

According to the logs, this is the full task graph before it's reduced and there are a lot of components missing in it: https://firefoxci.taskcluster-artifacts.net/HB9ZUbeESpGtZX1b-F61xw/0/public/full-task-graph.json

For example, [`feature-findinpage`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/findinpage/build.gradle#L31) has a dependency on `browser-state` (which I modified [in my PR](https://github.com/mozilla-mobile/android-components/pull/8250/files#diff-5b5de9adf69f383f48292ad741e73676)), so I would have expected that component to be rebuilt. However, I don't see it in the `full-task-graph.json` list to begin with, so that might be why it has been ignored?

cc: @mozbhearsum or @JohanLorenzo

**Comment by mozbhearsum** [comment]
I will take a look later today.

**Comment by mcomella** [comment]
> For this PR, I've touched browser-session and browser-state, so I would have expected all components that have those two as a dependency to be rebuilt: #8250

@jonalmeida Did the public API of these modules change? If not, it's _possible_ (I dunno) that you could re-use the modules that depend on it without recompilation if they're looking up the public API by name in the bytecode.

---

Assuming the lack of compilation is unintentional, this may not be the cause but I want to make you aware of it: over a month ago, Gradle configuration on demand was enabled: https://github.com/mozilla-mobile/android-components/pull/7631 At the gradle level, this will only configure tasks if they're necessary for the build – I wonder if 1) gradle is building the wrong graph under the hood rather than TaskCluster picking up the wrong graph or 2) TaskCluster reads a version of the graph before it's entirely complete.

@NotWoods Are there other gradle changes that have been made recently that could have impacted the TaskCluster task graph?

**Comment by mozbhearsum** [comment]
For the record, we run commands like this to determine dependencies: `/gradlew browser-session:dependencies --configuration implementation`

...and we do that recursively for every changed component and its direct dependencies.

I reran the decision task locally with some extra logging (which I'll send a PR for for easier debugging in the future), and found:
```
2020-08-27 12:57:31,051 - INFO - Found dependencies for 'browser-session':
2020-08-27 12:57:31,052 - INFO - concept-engine
support-ktx
support-utils
2020-08-27 12:57:36,465 - INFO - Found dependencies for 'concept-engine':
2020-08-27 12:57:36,466 - INFO - support-ktx
2020-08-27 12:57:41,485 - INFO - Found dependencies for 'support-ktx':
2020-08-27 12:57:41,485 - INFO - support-utils
support-base
2020-08-27 12:57:45,995 - INFO - Found dependencies for 'support-utils':
2020-08-27 12:57:45,996 - INFO - support-base
2020-08-27 12:57:50,417 - INFO - Found dependencies for 'support-base':
2020-08-27 12:57:50,417 - INFO - 
2020-08-27 12:57:55,145 - INFO - Found dependencies for 'browser-state':
2020-08-27 12:57:55,146 - INFO - concept-engine
support-ktx
support-utils
```

Are there some dependencies missing for any of the listed components?

**Comment by mozbhearsum** [comment]
Oh wait - I just realized that this issue is saying that _downstream_ dependencies aren't built when upstreams are changed. Which....is a total oversight from my original implementation of this. I'll work up a fix.
