### ISSUE TITLE
Change default top sites for different regions

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#8491]
This issue is to address default top sites that are currently present in existing users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7362)

**Comment by jonalmeida** [comment]
Since you have a top sites database, you could have a separate table that stores the different defaults for each region.

Then using `LocationService.fetchRegion` you could fetch the correct region and query the DB table.

This would also solve [the strict mode violations](https://github.com/mozilla-mobile/fenix/issues/14252) you see in Fenix from storing/reading this from a pref.

**Comment by pocmo** [comment]
For search in particular we may need to define a way to define a "generic" "search with google" tile and let the search code resolve that when needed. What code and region the user is in depends on that code and may change over time.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796263

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
