### ISSUE TITLE
Build tree only takes implementation dependencies into account

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8540]
See the following PR:
https://github.com/mozilla-mobile/android-components/pull/8509

It modifies the `browser-state` component. And this is the build group that was generated:
https://firefox-ci-tc.services.mozilla.com/tasks/groups/T4jWfVTTRKW7YrcCKCPHXA

I noticed that _at least_ `feature-media` is missing, which has an indirect dependency on `browser-state`:
- depends on browser-session: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/media/build.gradle#L37
- which depends on browser-state: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/session/build.gradle#L31

**Comment by pocmo** [comment]
CC @JohanLorenzo @mozbhearsum

**Comment by pocmo** [comment]
I think we should declare a direct dependency, because we use it directly in `feature-media`. Nevertheless I think it should have built? 🤔

**Comment by mozbhearsum** [comment]
Quick thoughts (I'll dig more later): I _think_ this is because we use `implementation` dependencies find finding them, and `browser-session` has an `api` dependency on `browser-state`.

Two possible ideas to solve:
1) Change the dependency type (or add it to `implementation` too).
2) Look at `implementation` and `api` dependencies when calculating them in taskgraph. This would probably mean running two commands in https://github.com/mozilla-mobile/android-components/blob/master/taskcluster/ac_taskgraph/loader/build_config.py#L46 instead of one, unless we can make gradle do both in one invocation.

**Comment by mozbhearsum** [comment]
I had a look around the tree and I found a few other cases where we may have non-implementation dependencies that matter here:
https://github.com/mozilla-mobile/android-components/blob/2bc8627e160196c544bb8584cf926765fce4889c/samples/browser/build.gradle#L131
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko-beta/build.gradle#L74
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko/build.gradle#L73
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko-nightly/build.gradle#L74
https://github.com/mozilla-mobile/android-components/blob/2bc8627e160196c544bb8584cf926765fce4889c/components/lib/crash/build.gradle#L76
https://github.com/mozilla-mobile/android-components/blob/2bc8627e160196c544bb8584cf926765fce4889c/components/service/location/build.gradle#L33

@pocmo - do we need to consider these, too?

**Comment by mozbhearsum** [comment]
I should add -- each additional configuration we look at will add about ~35s to the decision task, so if we can centralize build dependencies in implementation & api, that seems like it would be better. But it's not the end of the world to check other ones, it just slows down CI a bit.
