### ISSUE TITLE
SystemEngineSession.loadData sets url to "data:..." instead of something user friendly

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#865]
In firefox-tv, we use `SystemEngineSession.loadData` to [load error page content](https://github.com/mozilla-mobile/firefox-tv/blob/e869530c2be44344627723c83defdf3af395a2be/app/src/main/java/org/mozilla/focus/engine/CustomContentRequestInterceptor.kt#L69). However, this method sets the url to a data URI:

![screenshot_1537908683](https://user-images.githubusercontent.com/759372/46042400-1e5ae400-c0ca-11e8-9cac-63bc20eb2db9.png)

This is not very user friendly and it'd be great to override to something like, "firefox:neterror". afaik, `WebView` provides this functionality: instead of calling `loadData`, we can call [`loadDataWithBaseURL`](https://developer.android.com/reference/android/webkit/WebView#loadDataWithBaseURL(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)) and pass in the desired URL to display. The line to change is here:
https://github.com/mozilla-mobile/android-components/blob/14fdb2d78a009bc0dc782cb28898a6f5d3128c23/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt#L71

And it's essentially a call through.

We're tracking this issue in https://github.com/mozilla-mobile/firefox-tv/issues/1193

**Comment by mcomella** [comment]
fwiw, Jonathan mentioned this was intentional so I tried to work around this briefly but I don't think we can get a reference to the WebView:
```kotlin
fun EngineSession.load() {
    if (this is SystemEngineSession) {
        loadR()
    }
}

fun SystemEngineSession.loadR() {
    // Can't access `currentView` because it's internal.
}
```

So we'd have to do some view hierarchy manipulation.

**Comment by jonalmeida** [comment]
I've created [PR #866][1] to add support for `loadDataWithBaseUrl` as requested, but in my attempt to have something like `firefox:neterr` implemented in the FFTV project, I found myself re-writing the [same Focus code][2] that shows `about:focus` and `about:rights` in the urlbar:

```kotlin
override fun onLocationChange(session: GeckoSession, url: String) {
    var desiredUrl = url
    // Save internal data: urls we should override to present focus:about, focus:rights
    if (isLoadingInternalUrl) {
        if (currentUrl == LocalizedContent.URL_ABOUT) {
            internalAboutData = desiredUrl
        } else if (currentUrl == LocalizedContent.URL_RIGHTS) {
            internalRightsData = desiredUrl
        }
        isLoadingInternalUrl = false
        desiredUrl = currentUrl
    }

    // Check for internal data: urls to instead present focus:rights, focus:about
    if (!TextUtils.isEmpty(internalAboutData) && internalAboutData == desiredUrl) {
        desiredUrl = LocalizedContent.URL_ABOUT
    } else if (!TextUtils.isEmpty(internalRightsData) && internalRightsData == desiredUrl) {
        desiredUrl = LocalizedContent.URL_RIGHTS
    }

    currentUrl = desiredUrl
    callback?.onURLChanged(desiredUrl)
}
```

I see two options here:

1. Since I believe the motivation is for having a UX that shows something better in the url bar, we can still do this the same way in the `onLocationChange` for the session observer **without needing this patch to go in**.
2. However, with this patch, it would mean that the SystemEngine would set `about:blank` in the URL for error pages **without FFTV needing to make any code changes** which (imo) is also a slightly better UX than the current.

![screenshot_1537933769](https://user-images.githubusercontent.com/1370580/46056436-9c48da80-c11e-11e8-8e5b-a89521046cf5.png)

[1]: https://github.com/mozilla-mobile/android-components/pull/866
[2]: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt#L472-L494

**Comment by pocmo** [comment]
For error pages I expect the URL to not change at all.

If I go to http://www.sdfksjadfkjsahdfkjashdfkjsadhf.com/ then I am still on this page but just see the error page content.

In `onLoadRequest()` we optionally return an `InterceptionResponse`. I wonder if we should do the same for `onErrorRequest()` too (`ErrorResponse`?) - if the app wants to provide an error page. We then can call `loadDataWithBaseUrl()` in the SystemWebView implementation - and in the GeckoView implementation something else. This avoids that the app needs to figure out what the right things is if it just wants to show an error page.
