### ISSUE TITLE
Add Firebase Crashlytics support

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#8794]
Current lib-crash does not support Firebase Crashlytics.  Add support and mechanism to allow user to opt-in / opt-out of Crashlytics.

**Comment by jonalmeida** [comment]
Spoke offline with Roger, we want to use the latest version of Firebase Crashlytics but we're blocked on it because Firebase libraries work on particular versions. The version of Crashlytics that is compatible with our current version of Cloud Messaging according to [the BoM](https://firebase.google.com/support/release-notes/android#bom_v16-0-0) is 2.9.9. The current version is 17.2.2.

If we unblock upgrading FCM (https://github.com/mozilla-mobile/android-components/issues/4819) we can get to the latest version.

**Comment by rocketsroger** [comment]
From investigation and testing this change is purely on the app side.  I've opened an issue to track this https://github.com/mozilla-mobile/fenix/issues/17172.  Closing this since no change on A-C is needed.
