### ISSUE TITLE
A-C Team doesn't have permission anymore to re-run failed tasks

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#8833]
Both @st3fan and @csadilek ran into this.

For example https://github.com/mozilla-mobile/android-components/pull/8821 with https://firefox-ci-tc.services.mozilla.com/tasks/groups/BZp0tqCTRaKf1kCxnci9Og has a failed task `build-support-migration`. When I try to re-run it, I get the following error:

The role hook-id:project-mobile/in-tree-action-1-generic/9e64c87652 does not have sufficient scopes to create the task:

Client ID static/taskcluster/hooks does not have sufficient scopes and is missing the following scopes:

```
{
  "AllOf": [
    "assume:repo:github.com/mozilla-mobile/android-components:action:generic",
    "queue:route:tc-treeherder.v2.android-components.3ff68f30d2423ebbadd6a742348cf2fece1e7e27",
    "queue:scheduler-id:mobile-level-3",
    {
      "AnyOf": [
        "queue:create-task:highest:mobile-3/decision",
        "queue:create-task:very-high:mobile-3/decision",
        "queue:create-task:high:mobile-3/decision",
        "queue:create-task:medium:mobile-3/decision",
        "queue:create-task:low:mobile-3/decision",
        "queue:create-task:very-low:mobile-3/decision",
        "queue:create-task:lowest:mobile-3/decision"
      ]
    }
  ]
}
```

This request requires the client to satisfy the following scope expression:

```
{
  "AllOf": [
    "assume:repo:github.com/mozilla-mobile/android-components:action:generic",
    "queue:route:checks",
    "queue:route:tc-treeherder.v2.android-components.3ff68f30d2423ebbadd6a742348cf2fece1e7e27",
    "queue:scheduler-id:mobile-level-3",
    {
      "AnyOf": [
        "queue:create-task:highest:mobile-3/decision",
        "queue:create-task:very-high:mobile-3/decision",
        "queue:create-task:high:mobile-3/decision",
        "queue:create-task:medium:mobile-3/decision",
        "queue:create-task:low:mobile-3/decision",
        "queue:create-task:very-low:mobile-3/decision",
        "queue:create-task:lowest:mobile-3/decision"
      ]
    }
  ]
}
```

Pretty sure that I was previously able to do this.

**Comment by st3fan** [comment]
@mozilla-mobile/releng  help please - this is blocking our ability to create A-C releases.

**Comment by JohanLorenzo** [comment]
Thanks for letting us know!

So, rerunning single tasks in PRs is not supported. That's because of a limitation of the Taskcluster scope model when it comes to Github PRs. Basically in this case, Taskcluster runs code from an arbitrary repo, and we don't have a clean way to allow them all.

I see this PR was made from the a-c repo itself, so we could technically allow this very repo for PRs. Actually I believe it should work. That likely explains why you get level-3 errors while this is a PR (which is level 1). I'll have to look into why things  are mixed up this way.

Anyway, in the meantime, the best workaround is to close and reopen the PR. It will rerun **everything** but it'll do it in a secure way

**Comment by jonalmeida** [comment]
We can now request permissions [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Infrastructure%20%26%20Operations&component=Infrastructure%3A%20LDAP) to be part of the `mobile_eng_ops` group.
