### ISSUE TITLE
Would it be possible to have 2 engines running at the same time?

### ISSUE THREAD

**Issue by paulrouget** [mozilla-mobile/android-components#889]
We are thinking about adding Servo to Android Component. We want to be able to have browser with 2 kind of tabs: Gecko and Servo. At the same time. Would that be possible with Android component?

**Comment by pocmo** [comment]
> We are thinking about adding Servo to Android Component. 

Wow, that's awesome! 💯 

> We want to be able to have browser with 2 kind of tabs: Gecko and Servo. At the same time. Would that be possible with Android component?

There are two answers:

(1) Yes, it is for example possible right now to use `browser-engine-gecko` (GeckoView) and `browser-engine-system` (WebView) in the same app. However we can't use two GeckoView builds (e.g. `browser-engine-gecko` and `browser-engine-gecko-nightly`) because they use the same Java class names and that causes a conflict. So as long as Servo doesn't re-use GeckoView classes without renaming them (or the package) this should just work.

(2) Our `browser-session` component which deals with things like "what tabs are open and what data is associated with them?" currently only works with a single engine. However we could look into opening this up. Some time ago I was thinking about writing a sample app that would load a URL in WebView and GeckoView concurrently - for comparison. This sample has more or less the same requirements: Two engines used at the same time.

**Comment by paulrouget** [comment]
> currently only works with a single engine

Servo is not ready for full-web support. We'd like to be able to turn Servo on just for specific pages where it performs well. So this will be needed.

We are investigating the possibility of integrating Servo in Firefox Reality via Android Component. As of now, this is obviously impossible because of all the VR APIs (see https://github.com/MozillaReality/FirefoxReality/issues/80) but that might be an option in the future.
