### ISSUE TITLE
Use MediaSession Metadata in Media Notification

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9170]
Currently we use the URL's title and icon for media notification.  With the new `MediaSession` API, update to use the metadata in the notifications.

**Comment by seranpion** [comment]
Hello.

I see things not working as expected on this subject as of today.

The MediaSession notification is using the page title and URL instead of the `MediaSession.Metadata` properties (title & artist).

I have noticed this on Firefox for Android version 104 (OS: LineageOS 18.1 (Android 11, API level 30)).

And I can't open a new issue with the correct type for this.
