### ISSUE TITLE
Figure out how to write changelog during the sprint

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#954]
To make releases faster (less prep work) it would be helpful to have the changelog ready at the time we release. Ideally we write the changelog entry together with the code changes.

* Option 1: We directly edit the changelog file and this change is part of the commit / PR. We may need some tooling to make sure we do not forget that. Either we have some kind of "In Development" section in the changelog or we just hide the new entries between comment tags until we actually release that.

* Option 2: We generate the changelog from content in the commit messages. We'd need to define some syntax and we'd need some tooling to actually generate this for a release and add it to the changelog. A bot that posts the changelog entry in markdown to the PR would be helpful to see how the commit will affect the changelog.

A foundation for "Option 2" may be the "Conventional Commits" spec (@Amejia481 mentioned that on Slack a while ago). We may want to have a more AC-specific syntax or mechanism for grouping changes by component. Also we should still be able to write "rich" entries.
  * https://www.conventionalcommits.org/en/v1.0.0-beta.2/
  * https://github.com/conventional-changelog/conventional-changelog

**Comment by pocmo** [comment]
I like how Option 2 can be automated a lot and how we can have tooling for a lot of the steps. In theory taskcluster could do everything on its own in a release task. It will be complicated to get contributors adhere to that standard - tooling can only help a bit there. Editing and re-pushing contributor commits/PRs is inconvenient.

I like about Option 1 that it can be asynchronously. You can easily add, edit and extend the entries easily in later commits. In Option 2 you would need to wait for the changelog to be generated until you could manually change things in it.

**Comment by jonalmeida** [comment]
Both options sound good to me, but I'd lean more toward Option 1. In either case, I'd like some ability to edit the changelog.

**Option 1:** let's to decide to selectively add into the changelog or if it's a trivial fix that isn't worth mentioning.
> Either we have some kind of "In Development" section in the changelog or we just hide the new entries between comment tags until we actually release that.

This is nice because you can then see what's the current state of master when you look at the changelog.

**Option 2:** should allow us to edit the changelog to remove any commit messages which don't add much value to the changelog. (e.g. "Fixes typos")

We also add code snippets in our changelog now, so I believe those would also have to go into the commit message/PR for option 2, which would be easier to do with 1.

**Comment by grigoryk** [comment]
While I like I generally like Option 2, one caveat with it is that it must clearly decouple commits from an entry in the changelog. @jonalmeida gave one example above of that (clean-up commits, etc); I'm thinking about a fairly typical (for me, anyway) "a change is split over multiple commits which form a 'story'" pattern - e.g. Pre, Part 1, Part 2, Post.... Which of these commits contribute to the changelog? Can multiple commits contribute differently, describing parts of the functionality? Squashing them as work-around is possible (and the changelog commit would be in the squash commit entry), but then we'd loose that commit story and reduce historical usefulness of our commit log.

I like Option 1 because it clearly decouples our changelogs from how we structure our commits, and is asynchronous in nature as @pocmo described.

**Comment by pocmo** [comment]
For Option 2: I think that not every commit will need to have a changelog entry (controllable by syntax). And it's always possible to change/extend the changelog once it has been generated.

**Comment by Amejia481** [comment]
I believe that we can find I balance between both options where we can automate the process without losing flexibility.

We can use option 2 and before the release generate the change log file and add any additional bit that must be in the CHANGELOG.

**Comment by pocmo** [comment]
How about we start with Option 1 because we can start with that NOW without any tooling and then expand the tooling and maybe get to Option 2 if we still think it makes sense.

With sprint 0.27.0 we could add a `0.27.0-SNAPSHOT` section to the changelog. With every PR/commit we also update the changelog. On release day we just need to drop `-SNAPSHOT` and are done. For (partial) dot releases we just move a couple of things around. We can start our "tooling" by adding a PR-template that makes sure we updated the changelog.

**Comment by pocmo** [comment]
Closing. Let's see how that works in the next sprint(s).
