### ISSUE TITLE
TabListAction.RestoreAction does not update state selected tab when opening from collections 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#9593]
https://github.com/mozilla-mobile/android-components/blob/4aaaea6ca280d31697546f1d9357eda6ddfd29c3/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt#L134

When we restore a tab we check if another tab is already selected before selecting the restored tab. This is something that is useful in some cases, but there are use cases where we should update the selected tab even if there already is another one selected. For example when opening a tab from collections: https://github.com/mozilla-mobile/fenix/issues/17730.

On switching from `SessionManager` to `BrowserStore` here: https://github.com/mozilla-mobile/fenix/commit/87d6f323744a15a419202aac791ca974623cbbc5  we do not select and reload the newly opened tab anymore (the one that was selected in `sessionManager`) but the already selected tab in `state`.

@pocmo My question would be if we should remove the check for the existing selected session (the comment mentions it might mess up cases with tabs from intents) or should we add another optional boolean parameter like `forceSelection` or something that default to `false` but can be used in cases where we want to force a new selection (opening tab from collections that also uses restore).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8155)

**Comment by pocmo** [comment]
Yeah, we definitely need this check for the intent case, otherwise we restore (which happens async) and then override the selected tab that we just created from the incoming intent.

I think I saw another bug about the order of tabs not necessarily be right either: We are adding the restored tabs at the beginning to have visually the impression of they appeared first and then everything else (e.g. tabs from intents).

I wonder if instead of restore (which has all the behaviors above and that we want explicitly) whether we should go through an "add tab" use case instead of a "restore" use case - or divide them differently, we have two very different kinds of "restore".

**Comment by mcarare** [comment]
@pocmo Are there other different things we want to do in the chain of method calls from `RestoreUseCase` to `TabListReducer`? I am not very familiar with all the notification behavior in `SessionManager`.

If we do, we can create another use case. But if we only want to change the actions in the reducer (adding tabs in a different order, select the restored tab) maybe we should just pass another parameter to `RestoreUseCase` (and either pass it forward to the reducer or generate another `TabListAction`) instead of duplicating code in `TabsUseCases`, `SessionManager`, `BrowserAction` etc.

**Comment by pocmo** [comment]
I want to avoid that we add a bunch of things to `RestoreUseCase` and then its duplicating the functionality of `AddNewTabUseCase`. If we keep the meaning "restore" then I guess what you need is an "add" of multiple tabs (with the ability to update the selection).

**Comment by mcarare** [comment]
Temporarily unassigning myself so it can be picked up by someone else while I handle some older items from my backlog.
