### ISSUE TITLE
Geckoview Cookie Problem

### ISSUE THREAD

**Issue by ChiY119** [mozilla-mobile/android-components#9737]
My app is using Geckoview and Webview, together.
My app is trying to login to our website via API communication.
App login successfully to website on API communication and I saved the cookie info.
When I'm calling website domain in app's webview, saved Cookie was used. 
So I can enter the website without any login process via app's webview by using API login .
But, When I'm calling this domain on Geckoview, I think, cookie is not being used.
Website login screen  is appearing to me on Geckoview.
I used the okhttp library to login API of website.
///////////////
How can I solve this issue?
Really, I want to login without any login page on Geckoview by using Cookie.
If you can reply to me, thanks.

**Comment by pocmo** [comment]
Are you using GeckoView directly or through our `browser-engine-gecko*` component in this repository?

I don't fully understand your configuration. You mention WebView but also okhttp for the login?

If you are using `okhttp` then maybe have a look at [`GeckoWebExecutor`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoWebExecutor.html), which is a HTTP client that comes with GeckoView and can use the same cookie storage.

If you are using WebView or have to use okhttp then the following bugzilla bug may be something to follow since GeckoView does not have a cookie API yet:
https://bugzilla.mozilla.org/show_bug.cgi?id=1035417
