### ISSUE TITLE
Deprecate and remove service-pocket

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#9764]
Currently, service-pocket has two sets of functionality that have been deprecated upstream:
- global video recommendations: this was used for fire TV video recommendations but it is no longer being updated upstream and the feature was removed from the product because the cost of curation was more expensive than the feature was worth
- Pocket Listen prototype: I wrote a prototype for Echo Show to incorporate Pocket Listen functionality (the device reads an article to you using text-to-speech). However, this prototype went nowhere and was never sent to production so this API is unused. Furthermore, I believe the Pocket back-end uses a different system for their TTS than Pocket Listen so I doubt this API is useful anymore

Since these APIs are not useful and I see no future in which they're useful, I think we should remove them. One counter-point to this is that we may add support for pocket suggested articles in some future (I don't know if it's on the roadmap) and the existing infrastructure could be helpful. There was a WIP PR opened in https://github.com/mozilla-mobile/android-components/pull/9193 for that functionality but it never landed.

To be explicit, I do not intend to remove it myself: it's not bothering anybody so it's not urgent and I have other things on my plate. However, I thought I'd file in case someone wanted to keep things clean around here. :)

CC @Mugurell who wrote the Pocket articles PR

**Comment by mcomella** [comment]
Also, BZ-1689332 was caused by still having this code around so, in general, removing inactive code could help prevent such issues in the future.

**Comment by Mugurell** [comment]
Thank you Michael!

Based on the discussions then my PR - https://github.com/mozilla-mobile/android-components/pull/9193 refactors out the support for video recommendations and Pocket Listen and will leave the service-pocket with support for periodic refreshes of Pocket recommended articles that can be queries by AC clients.

Also want to ask @amedyne if this new functionality (showing Pocket articles recommendations) is still needed in the near future. Otherwise I think we can drop the entire component since the existing functionality is deprecated.

**Comment by Mugurell** [comment]
This component is still needed. Closing the ticket.
