### ISSUE TITLE
github api queries in taskcluster code need to handle pagination

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#9942]
The A-C build system limits the number of components that need to be rebuild for a PR by looking at what has actually changed. This works well, but it seems that _string changes_ are (sometimes?) excluded from this logic.

This specially affects the string import PRs. The following PR:

 * https://github.com/mozilla-mobile/android-components/pull/9929

Had a change in 

 * `components/ui/tabcounter/src/main/res/values-bg/strings.xml`

But the PR did not rebuild the `ui-tabcounter` component/task. Which would have failed because the linter would have detected an error in a changed string.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8406)

**Comment by bhearsum** [comment]
This is baffling. The decision task log shows that it's not detecting that file has changed (https://firefoxci.taskcluster-artifacts.net/D78ofdvxQp2tBDRh7zkIwg/0/public/logs/live_backing.log). And indeed, when I query the github API for that pull request, it's not in there: https://api.github.com/repos/mozilla-mobile/android-components/pulls/9929/files.

It looks like this is because we're not handling pagination on that API request. https://api.github.com/repos/mozilla-mobile/android-components/pulls/9929/files?per_page=100 returns that file.

**Comment by bhearsum** [comment]
We should probably just add a github library as a dependency, if it's easy too, rather than reimplement pagination handling.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795411

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
